use sea_orm_migration::prelude::*;

#[derive(DeriveMigrationName)]
pub struct Migration;

#[async_trait::async_trait]
impl MigrationTrait for Migration {
    async fn up(&self, manager: &SchemaManager) -> Result<(), DbErr> {
        manager
            .create_table(
                Table::create()
                    .table(UserProfiles::Table)
                    .col(
                        ColumnDef::new(UserProfiles::Id)
                            .string()
                            .not_null()
                            .primary_key(),
                    )
                    .col(ColumnDef::new(UserProfiles::UserId).string().not_null())
                    .col(
                        ColumnDef::new(UserProfiles::CreatedAt)
                            .big_integer()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(UserProfiles::UpdatedAt)
                            .big_integer()
                            .not_null(),
                    )
                    .col(ColumnDef::new(UserProfiles::CodingStyle).text().not_null())
                    .col(
                        ColumnDef::new(UserProfiles::Communication)
                            .text()
                            .not_null(),
                    )
                    .col(ColumnDef::new(UserProfiles::WorkHabits).text().not_null())
                    .col(
                        ColumnDef::new(UserProfiles::DomainKnowledge)
                            .text()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(UserProfiles::LearningState)
                            .text()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(UserProfiles::Version)
                            .integer()
                            .not_null()
                            .default(1),
                    )
                    .to_owned(),
            )
            .await?;

        manager
            .create_index(
                Index::create()
                    .name("idx_user_profiles_user_id")
                    .table(UserProfiles::Table)
                    .col(UserProfiles::UserId)
                    .to_owned(),
            )
            .await?;

        manager
            .create_table(
                Table::create()
                    .table(BehaviorEvents::Table)
                    .col(
                        ColumnDef::new(BehaviorEvents::Id)
                            .string()
                            .not_null()
                            .primary_key(),
                    )
                    .col(ColumnDef::new(BehaviorEvents::UserId).string().not_null())
                    .col(
                        ColumnDef::new(BehaviorEvents::EventType)
                            .string()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(BehaviorEvents::Timestamp)
                            .big_integer()
                            .not_null(),
                    )
                    .col(ColumnDef::new(BehaviorEvents::Context).text().not_null())
                    .col(ColumnDef::new(BehaviorEvents::Metadata).text().not_null())
                    .col(
                        ColumnDef::new(BehaviorEvents::InteractionId)
                            .string()
                            .null(),
                    )
                    .col(
                        ColumnDef::new(BehaviorEvents::CreatedAt)
                            .big_integer()
                            .not_null(),
                    )
                    .to_owned(),
            )
            .await?;

        manager
            .create_index(
                Index::create()
                    .name("idx_behavior_events_user_id")
                    .table(BehaviorEvents::Table)
                    .col(BehaviorEvents::UserId)
                    .to_owned(),
            )
            .await?;

        manager
            .create_index(
                Index::create()
                    .name("idx_behavior_events_timestamp")
                    .table(BehaviorEvents::Table)
                    .col(BehaviorEvents::Timestamp)
                    .to_owned(),
            )
            .await?;

        manager
            .create_table(
                Table::create()
                    .table(ExplicitPreferences::Table)
                    .col(
                        ColumnDef::new(ExplicitPreferences::Id)
                            .string()
                            .not_null()
                            .primary_key(),
                    )
                    .col(
                        ColumnDef::new(ExplicitPreferences::UserId)
                            .string()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(ExplicitPreferences::Category)
                            .string()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(ExplicitPreferences::SettingKey)
                            .string()
                            .not_null(),
                    )
                    .col(ColumnDef::new(ExplicitPreferences::Value).text().not_null())
                    .col(
                        ColumnDef::new(ExplicitPreferences::SetAt)
                            .big_integer()
                            .not_null(),
                    )
                    .to_owned(),
            )
            .await?;

        manager
            .create_index(
                Index::create()
                    .name("idx_explicit_prefs_user_id")
                    .table(ExplicitPreferences::Table)
                    .col(ExplicitPreferences::UserId)
                    .to_owned(),
            )
            .await?;

        manager
            .create_index(
                Index::create()
                    .name("idx_explicit_prefs_user_category_key")
                    .table(ExplicitPreferences::Table)
                    .col(ExplicitPreferences::UserId)
                    .col(ExplicitPreferences::Category)
                    .col(ExplicitPreferences::SettingKey)
                    .to_owned(),
            )
            .await?;

        Ok(())
    }

    async fn down(&self, manager: &SchemaManager) -> Result<(), DbErr> {
        manager
            .drop_table(Table::drop().table(ExplicitPreferences::Table).to_owned())
            .await?;
        manager
            .drop_table(Table::drop().table(BehaviorEvents::Table).to_owned())
            .await?;
        manager
            .drop_table(Table::drop().table(UserProfiles::Table).to_owned())
            .await?;
        Ok(())
    }
}

#[derive(Iden)]
pub enum UserProfiles {
    Table,
    Id,
    UserId,
    CreatedAt,
    UpdatedAt,
    CodingStyle,
    Communication,
    WorkHabits,
    DomainKnowledge,
    LearningState,
    Version,
}

#[derive(Iden)]
pub enum BehaviorEvents {
    Table,
    Id,
    UserId,
    EventType,
    Timestamp,
    Context,
    Metadata,
    InteractionId,
    CreatedAt,
}

#[derive(Iden)]
pub enum ExplicitPreferences {
    Table,
    Id,
    UserId,
    Category,
    SettingKey,
    Value,
    SetAt,
}
