use sea_orm_migration::prelude::*;

#[derive(DeriveMigrationName)]
pub struct Migration;

#[async_trait::async_trait]
impl MigrationTrait for Migration {
    async fn up(&self, manager: &SchemaManager) -> Result<(), DbErr> {
        manager
            .create_table(
                Table::create()
                    .table(KnowledgeEntities::Table)
                    .if_not_exists()
                    .col(
                        ColumnDef::new(KnowledgeEntities::Id)
                            .string()
                            .not_null()
                            .primary_key(),
                    )
                    .col(
                        ColumnDef::new(KnowledgeEntities::KnowledgeBaseId)
                            .string()
                            .not_null(),
                    )
                    .col(ColumnDef::new(KnowledgeEntities::Name).string().not_null())
                    .col(ColumnDef::new(KnowledgeEntities::EntityType).string().not_null())
                    .col(ColumnDef::new(KnowledgeEntities::Description).string().null())
                    .col(ColumnDef::new(KnowledgeEntities::SourcePath).string().not_null())
                    .col(ColumnDef::new(KnowledgeEntities::SourceLanguage).string().null())
                    .col(ColumnDef::new(KnowledgeEntities::Properties).json().not_null())
                    .col(ColumnDef::new(KnowledgeEntities::Lifecycle).json().null())
                    .col(ColumnDef::new(KnowledgeEntities::Behaviors).json().null())
                    .col(ColumnDef::new(KnowledgeEntities::Metadata).json().null())
                    .col(ColumnDef::new(KnowledgeEntities::CreatedAt).integer().not_null())
                    .col(ColumnDef::new(KnowledgeEntities::UpdatedAt).integer().not_null())
                    .to_owned(),
            )
            .await?;

        manager
            .create_table(
                Table::create()
                    .table(KnowledgeAttributes::Table)
                    .if_not_exists()
                    .col(
                        ColumnDef::new(KnowledgeAttributes::Id)
                            .string()
                            .not_null()
                            .primary_key(),
                    )
                    .col(
                        ColumnDef::new(KnowledgeAttributes::KnowledgeBaseId)
                            .string()
                            .not_null(),
                    )
                    .col(ColumnDef::new(KnowledgeAttributes::EntityId).string().not_null())
                    .col(ColumnDef::new(KnowledgeAttributes::Name).string().not_null())
                    .col(
                        ColumnDef::new(KnowledgeAttributes::AttributeType)
                            .string()
                            .not_null(),
                    )
                    .col(ColumnDef::new(KnowledgeAttributes::DataType).string().not_null())
                    .col(ColumnDef::new(KnowledgeAttributes::Description).string().null())
                    .col(ColumnDef::new(KnowledgeAttributes::IsRequired).boolean().not_null())
                    .col(ColumnDef::new(KnowledgeAttributes::DefaultValue).string().null())
                    .col(ColumnDef::new(KnowledgeAttributes::Constraints).json().null())
                    .col(ColumnDef::new(KnowledgeAttributes::ValidationRules).json().null())
                    .col(ColumnDef::new(KnowledgeAttributes::Metadata).json().null())
                    .col(ColumnDef::new(KnowledgeAttributes::CreatedAt).integer().not_null())
                    .col(ColumnDef::new(KnowledgeAttributes::UpdatedAt).integer().not_null())
                    .to_owned(),
            )
            .await?;

        manager
            .create_table(
                Table::create()
                    .table(KnowledgeRelations::Table)
                    .if_not_exists()
                    .col(
                        ColumnDef::new(KnowledgeRelations::Id)
                            .string()
                            .not_null()
                            .primary_key(),
                    )
                    .col(
                        ColumnDef::new(KnowledgeRelations::KnowledgeBaseId)
                            .string()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(KnowledgeRelations::SourceEntityId)
                            .string()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(KnowledgeRelations::TargetEntityId)
                            .string()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(KnowledgeRelations::RelationType)
                            .string()
                            .not_null(),
                    )
                    .col(ColumnDef::new(KnowledgeRelations::Description).string().null())
                    .col(ColumnDef::new(KnowledgeRelations::Properties).json().null())
                    .col(ColumnDef::new(KnowledgeRelations::Metadata).json().null())
                    .col(ColumnDef::new(KnowledgeRelations::CreatedAt).integer().not_null())
                    .col(ColumnDef::new(KnowledgeRelations::UpdatedAt).integer().not_null())
                    .to_owned(),
            )
            .await?;

        manager
            .create_table(
                Table::create()
                    .table(KnowledgeFlows::Table)
                    .if_not_exists()
                    .col(
                        ColumnDef::new(KnowledgeFlows::Id)
                            .string()
                            .not_null()
                            .primary_key(),
                    )
                    .col(
                        ColumnDef::new(KnowledgeFlows::KnowledgeBaseId)
                            .string()
                            .not_null(),
                    )
                    .col(ColumnDef::new(KnowledgeFlows::Name).string().not_null())
                    .col(ColumnDef::new(KnowledgeFlows::FlowType).string().not_null())
                    .col(ColumnDef::new(KnowledgeFlows::Description).string().null())
                    .col(ColumnDef::new(KnowledgeFlows::SourcePath).string().not_null())
                    .col(ColumnDef::new(KnowledgeFlows::Steps).json().not_null())
                    .col(ColumnDef::new(KnowledgeFlows::DecisionPoints).json().null())
                    .col(ColumnDef::new(KnowledgeFlows::ErrorHandling).json().null())
                    .col(ColumnDef::new(KnowledgeFlows::Preconditions).json().null())
                    .col(ColumnDef::new(KnowledgeFlows::Postconditions).json().null())
                    .col(ColumnDef::new(KnowledgeFlows::Metadata).json().null())
                    .col(ColumnDef::new(KnowledgeFlows::CreatedAt).integer().not_null())
                    .col(ColumnDef::new(KnowledgeFlows::UpdatedAt).integer().not_null())
                    .to_owned(),
            )
            .await?;

        manager
            .create_table(
                Table::create()
                    .table(KnowledgeInterfaces::Table)
                    .if_not_exists()
                    .col(
                        ColumnDef::new(KnowledgeInterfaces::Id)
                            .string()
                            .not_null()
                            .primary_key(),
                    )
                    .col(
                        ColumnDef::new(KnowledgeInterfaces::KnowledgeBaseId)
                            .string()
                            .not_null(),
                    )
                    .col(ColumnDef::new(KnowledgeInterfaces::Name).string().not_null())
                    .col(
                        ColumnDef::new(KnowledgeInterfaces::InterfaceType)
                            .string()
                            .not_null(),
                    )
                    .col(ColumnDef::new(KnowledgeInterfaces::Description).string().null())
                    .col(ColumnDef::new(KnowledgeInterfaces::SourcePath).string().not_null())
                    .col(ColumnDef::new(KnowledgeInterfaces::InputSchema).json().not_null())
                    .col(ColumnDef::new(KnowledgeInterfaces::OutputSchema).json().not_null())
                    .col(ColumnDef::new(KnowledgeInterfaces::ErrorCodes).json().null())
                    .col(
                        ColumnDef::new(KnowledgeInterfaces::CommunicationPattern)
                            .string()
                            .null(),
                    )
                    .col(ColumnDef::new(KnowledgeInterfaces::Version).string().null())
                    .col(ColumnDef::new(KnowledgeInterfaces::Metadata).json().null())
                    .col(ColumnDef::new(KnowledgeInterfaces::CreatedAt).integer().not_null())
                    .col(ColumnDef::new(KnowledgeInterfaces::UpdatedAt).integer().not_null())
                    .to_owned(),
            )
            .await?;

        manager
            .create_index(
                Index::create()
                    .name("idx_knowledge_entities_kb_id")
                    .table(KnowledgeEntities::Table)
                    .col(KnowledgeEntities::KnowledgeBaseId)
                    .to_owned(),
            )
            .await?;

        manager
            .create_index(
                Index::create()
                    .name("idx_knowledge_attributes_entity_id")
                    .table(KnowledgeAttributes::Table)
                    .col(KnowledgeAttributes::EntityId)
                    .to_owned(),
            )
            .await?;

        manager
            .create_index(
                Index::create()
                    .name("idx_knowledge_relations_source")
                    .table(KnowledgeRelations::Table)
                    .col(KnowledgeRelations::SourceEntityId)
                    .to_owned(),
            )
            .await?;

        manager
            .create_index(
                Index::create()
                    .name("idx_knowledge_relations_target")
                    .table(KnowledgeRelations::Table)
                    .col(KnowledgeRelations::TargetEntityId)
                    .to_owned(),
            )
            .await?;

        Ok(())
    }

    async fn down(&self, manager: &SchemaManager) -> Result<(), DbErr> {
        manager
            .drop_table(Table::drop().table(KnowledgeInterfaces::Table).to_owned())
            .await?;
        manager
            .drop_table(Table::drop().table(KnowledgeFlows::Table).to_owned())
            .await?;
        manager
            .drop_table(Table::drop().table(KnowledgeRelations::Table).to_owned())
            .await?;
        manager
            .drop_table(Table::drop().table(KnowledgeAttributes::Table).to_owned())
            .await?;
        manager
            .drop_table(Table::drop().table(KnowledgeEntities::Table).to_owned())
            .await?;
        Ok(())
    }
}

#[derive(Iden)]
pub enum KnowledgeEntities {
    Table,
    Id,
    KnowledgeBaseId,
    Name,
    EntityType,
    Description,
    SourcePath,
    SourceLanguage,
    Properties,
    Lifecycle,
    Behaviors,
    Metadata,
    CreatedAt,
    UpdatedAt,
}

#[derive(Iden)]
pub enum KnowledgeAttributes {
    Table,
    Id,
    KnowledgeBaseId,
    EntityId,
    Name,
    AttributeType,
    DataType,
    Description,
    IsRequired,
    DefaultValue,
    Constraints,
    ValidationRules,
    Metadata,
    CreatedAt,
    UpdatedAt,
}

#[derive(Iden)]
pub enum KnowledgeRelations {
    Table,
    Id,
    KnowledgeBaseId,
    SourceEntityId,
    TargetEntityId,
    RelationType,
    Description,
    Properties,
    Metadata,
    CreatedAt,
    UpdatedAt,
}

#[derive(Iden)]
pub enum KnowledgeFlows {
    Table,
    Id,
    KnowledgeBaseId,
    Name,
    FlowType,
    Description,
    SourcePath,
    Steps,
    DecisionPoints,
    ErrorHandling,
    Preconditions,
    Postconditions,
    Metadata,
    CreatedAt,
    UpdatedAt,
}

#[derive(Iden)]
pub enum KnowledgeInterfaces {
    Table,
    Id,
    KnowledgeBaseId,
    Name,
    InterfaceType,
    Description,
    SourcePath,
    InputSchema,
    OutputSchema,
    ErrorCodes,
    CommunicationPattern,
    Version,
    Metadata,
    CreatedAt,
    UpdatedAt,
}
