import json
import os

base = r"D:\OneManager\AxAgent\src\i18n\locales"

# === KOREAN (ko.json) translations ===
ko = {
    "settings.scheduler.customTasks": "사용자 정의 작업",
    "settings.scheduler.addTask": "작업 추가",
    "settings.scheduler.editTask": "작업 편집",
    "settings.scheduler.taskName": "작업 이름",
    "settings.scheduler.taskDescription": "설명",
    "settings.scheduler.intervalHours": "간격 (시간)",
    "settings.scheduler.nextRunAt": "다음 실행",
    "settings.scheduler.lastRunAt": "마지막 실행",
    "settings.scheduler.noTasks": "사용자 정의 작업이 없습니다",
    "settings.scheduler.createTask": "작업 생성",
    "settings.scheduler.updateTask": "작업 업데이트",
    "settings.scheduler.deleteTask": "작업 삭제",
    "settings.scheduler.deleteTaskConfirm": "이 작업을 삭제하시겠습니까?",
    "settings.scheduler.pauseTask": "일시 정지",
    "settings.scheduler.resumeTask": "재개",
    "settings.scheduler.taskActive": "활성",
    "settings.scheduler.taskPaused": "일시 정지됨",
    "settings.scheduler.taskDisabled": "비활성화됨",
    "settings.scheduler.selectInterval": "간격 선택",
    "settings.scheduler.once": "한 번",
    "settings.scheduler.daily": "매일",
    "settings.scheduler.weekly": "매주",
    "settings.scheduler.monthly": "매월",
    "settings.scheduler.schedule": "일정",
    "settings.scheduler.scheduleSettings": "일정 설정",
    "settings.scheduler.scheduleType": "일정 유형",
    "settings.scheduler.selectScheduleType": "일정 유형 선택",
    "settings.scheduler.scheduleInterval": "간격",
    "settings.scheduler.scheduleDaily": "매일",
    "settings.scheduler.scheduleWeekly": "매주",
    "settings.scheduler.scheduleMonthly": "매월",
    "settings.scheduler.scheduleAdvanced": "고급",
    "settings.scheduler.weekdays": "요일",
    "settings.scheduler.monday": "월",
    "settings.scheduler.tuesday": "화",
    "settings.scheduler.wednesday": "수",
    "settings.scheduler.thursday": "목",
    "settings.scheduler.friday": "금",
    "settings.scheduler.saturday": "토",
    "settings.scheduler.sunday": "일",
    "settings.scheduler.timeRanges": "시간 범위",
    "settings.scheduler.startTime": "시작",
    "settings.scheduler.endTime": "종료",
    "settings.scheduler.addTimeRange": "시간 범위 추가",
    "settings.scheduler.monthDay": "날짜",
    "settings.scheduler.dayOfMonth": "{{day}}일",
    "settings.scheduler.selectDayOfMonth": "날짜 선택",
    "settings.scheduler.excludeHolidays": "공휴일 제외",
    "settings.scheduler.excludeCustomDates": "사용자 정의 날짜 제외",
    "settings.scheduler.enterExcludeDates": "제외할 날짜 입력 (YYYY-MM-DD)",
    "settings.scheduler.intervalDesc": "{{hours}}시간마다",
    "settings.scheduler.dailyDesc": "매일",
    "settings.scheduler.weeklyDesc": "매주 {{days}}요일",
    "settings.scheduler.monthlyDesc": "매월 {{day}}일",
    "settings.scheduler.advancedDesc": "고급 일정",
    "settings.scheduler.selectTemplate": "템플릿 선택",
    "settings.scheduler.workflowTemplates": "워크플로 템플릿",
    "settings.scheduler.reportTemplates": "보고서 템플릿",
    "settings.scheduler.workflowCodeReview": "코드 리뷰 워크플로",
    "settings.scheduler.workflowBugFix": "버그 수정 워크플로",
    "settings.scheduler.workflowDocGen": "문서화 워크플로",
    "settings.scheduler.workflowTestGen": "테스트 생성 워크플로",
    "settings.scheduler.workflowRefactor": "리팩토링 워크플로",
    "settings.scheduler.workflowExplore": "코드 탐색 워크플로",
    "settings.scheduler.workflowPerformance": "성능 최적화 워크플로",
    "settings.scheduler.workflowKnowledgeExtract": "지식 추출 워크플로",
    "settings.scheduler.workflowKnowledgeToCode": "지식에서 코드로 워크플로",
    "settings.localTools.title": "로컬 도구",
    "settings.localTools.description": "내장 도구 활성화/비활성화 상태를 관리합니다. 비활성화된 도구는 Agent의 사용 가능한 도구 목록에 표시되지 않습니다.",
    "settings.localTools.groupFetch": "웹 가져오기",
    "settings.localTools.groupSearchFile": "파일 검색",
    "settings.localTools.groupFilesystem": "파일 시스템",
    "settings.localTools.groupSystem": "시스템 명령어",
    "settings.localTools.groupSearch": "웹 검색",
    "settings.localTools.groupKnowledge": "지식 베이스",
    "settings.localTools.groupStorage": "객체 저장소",
    "settings.localTools.groupSkills": "스킬 관리",
    "settings.localTools.groupSession": "세션 검색",
    "settings.localTools.groupMemory": "메모리 관리",
    "settings.tools.title": "도구 관리자",
    "settings.tools.tabBuiltin": "내장 도구",
    "settings.tools.tabMcp": "MCP 서버",
    "settings.tools.tabGenerated": "생성된 도구",
    "settings.tools.tabSemantic": "의미적 검사",
    "settings.generatedTools.title": "생성된 도구",
    "settings.generatedTools.description": "복합 스킬 분해에서 생성된 프롬프트 템플릿 도구입니다. 이 도구는 LLM을 사용하여 프롬프트를 실행해 기능을 시뮬레이션합니다.",
    "settings.generatedTools.toolName": "도구 이름",
    "settings.generatedTools.originalName": "원래 이름",
    "settings.generatedTools.createdAt": "생성일",
    "settings.generatedTools.deleteConfirm": "이 생성된 도구를 삭제하시겠습니까?",
    "settings.generatedTools.deleteSuccess": "삭제되었습니다",
    "settings.generatedTools.total": "{{count}}개의 생성된 도구",
    "settings.generatedTools.empty": "생성된 도구 없음",
    "settings.toolSemanticCheck.title": "도구 의미적 검사",
    "settings.toolSemanticCheck.description": "AI를 사용하여 유사한 도구를 찾고 기존 도구를 업그레이드합니다",
    "settings.toolSemanticCheck.searchPlaceholder": "도구 이름 또는 설명 입력",
    "settings.toolSemanticCheck.emptySearch": "검색어를 입력하세요",
    "settings.toolSemanticCheck.noMatches": "유사한 도구를 찾을 수 없습니다",
    "settings.toolSemanticCheck.empty": "검색어를 입력하여 유사한 도구를 찾으세요",
    "settings.toolSemanticCheck.matches": "{{count}}개 일치",
    "settings.toolSemanticCheck.checkingTool": "{{tool}}과(와) 유사한 도구 확인 중",
    "settings.toolSemanticCheck.similarity": "유사도",
    "settings.toolSemanticCheck.upgrade": "업그레이드",
    "settings.toolSemanticCheck.upgradeModalTitle": "도구 업그레이드",
    "settings.toolSemanticCheck.existingTool": "기존 도구",
    "settings.toolSemanticCheck.generatedTool": "생성된 도구",
    "settings.toolSemanticCheck.toolType": "도구 유형",
    "settings.toolSemanticCheck.noDescription": "설명 없음",
    "settings.toolSemanticCheck.performUpgrade": "업그레이드 실행",
    "settings.toolSemanticCheck.upgradeSuccess": "도구 업그레이드 제안이 생성되었습니다",
    "settings.toolSemanticCheck.upgradeSuggestion": "업그레이드 제안",
    "settings.toolSemanticCheck.reasoning": "추론",
    "settings.groupWorkspace": "작업 공간",
    "settings.defaultWorkspaceDir": "기본 작업 공간 디렉토리",
    "settings.userProfile.title": "사용자 프로필",
    "settings.userProfile.overview": "프로필 개요",
    "settings.userProfile.userId": "사용자 ID",
    "settings.userProfile.lastUpdated": "마지막 업데이트",
    "settings.userProfile.codingStyle": "코딩 스타일",
    "settings.userProfile.namingConvention": "명명 규칙",
    "settings.userProfile.indentationStyle": "들여쓰기 스타일",
    "settings.userProfile.commentStyle": "주석 스타일",
    "settings.userProfile.communication": "커뮤니케이션",
    "settings.userProfile.detailLevel": "상세 수준",
    "settings.userProfile.tone": "톤",
    "settings.userProfile.language": "언어",
    "settings.userProfile.confidence": "프로필 신뢰도",
    "settings.userProfile.loading": "프로필 로드 중...",
    "link.title": "링크",
    "link.searchGateways": "게이트웨이 검색",
    "link.noGateways": "게이트웨이 연결 없음",
    "link.selectGateway": "게이트웨이 연결 선택",
    "link.addGateway": "게이트웨이 연결 추가",
    "link.gatewayName": "연결 이름",
    "link.gatewayType": "게이트웨이 유형",
    "link.endpoint": "엔드포인트",
    "link.apiKey": "API 키",
    "link.apiKeyPlaceholder": "선택 사항, 비워두면 키 없음",
    "link.namePlaceholder": "예: OpenClaw-Prod",
    "link.nameRequired": "연결 이름을 입력하세요",
    "link.endpointRequired": "엔드포인트를 입력하세요",
    "link.addSuccess": "게이트웨이 연결 추가됨",
    "link.addFailed": "게이트웨이 연결 추가 실패",
    "link.deleteSuccess": "게이트웨이 연결 삭제됨",
    "link.deleteFailed": "게이트웨이 연결 삭제 실패",
    "link.deleteConfirm": "이 게이트웨이 연결을 삭제하시겠습니까?",
    "link.typeCustom": "사용자 정의",
    "link.statusConnected": "연결됨",
    "link.statusDisconnected": "연결 해제됨",
    "link.statusConnecting": "연결 중",
    "link.statusError": "오류",
    "link.connect": "연결",
    "link.disconnect": "연결 해제",
    "link.latency": "지연 시간",
    "link.overview": "개요",
    "link.models": "모델",
    "link.skills": "스킬",
    "link.policies": "정책",
    "link.newConversation": "새 대화",
    "link.syncedModels": "동기화된 모델",
    "link.syncedSkills": "동기화된 스킬",
    "link.lastSync": "마지막 동기화",
    "link.recentActivity": "최근 활동",
    "link.noActivity": "아직 활동 없음",
    "link.autoSyncModels": "모델 자동 동기화",
    "link.autoSyncSkills": "스킬 자동 동기화",
    "link.syncAllModels": "모든 모델 동기화",
    "link.syncAllSkills": "모든 스킬 동기화",
    "link.syncAllSuccess": "동기화 성공",
    "link.syncAllFailed": "동기화 실패",
    "link.pushModelsSuccess": "모델 푸시 성공",
    "link.pushModelsFailed": "모델 푸시 실패",
    "link.pushSkillsSuccess": "스킬 푸시 성공",
    "link.pushSkillsFailed": "스킬 푸시 실패",
    "link.modelName": "모델 이름",
    "link.providerName": "공급자",
    "link.syncStatus": "동기화 상태",
    "link.syncStatusSynced": "동기화됨",
    "link.syncStatusPending": "대기 중",
    "link.syncStatusFailed": "실패",
    "link.syncStatusNotSelected": "선택 안 됨",
    "link.skillName": "스킬 이름",
    "link.skillVersion": "버전",
    "link.noModels": "모델 동기화 기록 없음",
    "link.noSkills": "스킬 동기화 기록 없음",
    "link.push": "푸시",
    "link.routingPolicy": "라우팅 정책",
    "link.routeStrategy": "라우팅 전략",
    "link.roundRobin": "라운드 로빈",
    "link.leastLatency": "최저 지연",
    "link.weighted": "가중치",
    "link.modelFallback": "모델 폴백",
    "link.rateLimiting": "속도 제한",
    "link.globalRpm": "전역 RPM",
    "link.perModelRpm": "모델별 RPM",
    "link.tokenLimitPerMinute": "분당 토큰 제한",
    "link.unlimited": "무제한",
    "link.keyManagement": "키 관리",
    "link.keyRotation": "키 순환",
    "link.sequential": "순차",
    "link.random": "무작위",
    "link.keyFailover": "키 장애 조치",
    "link.savePolicy": "정책 저장",
    "link.policySaved": "정책 저장됨",
    "link.policySaveFailed": "정책 저장 실패",
    "link.noPolicy": "정책 구성 없음",
    "link.loadPolicy": "정책 로드",
    "profile.loading": "프로필 로드 중...",
    "profile.overview": "프로필 개요",
    "profile.userId": "사용자 ID",
    "profile.lastUpdated": "마지막 업데이트",
    "profile.codingStyle": "코딩 스타일",
    "profile.namingConvention": "명명 규칙",
    "profile.indentationStyle": "들여쓰기 스타일",
    "profile.commentStyle": "주석 스타일",
    "profile.communication": "커뮤니케이션",
    "profile.detailLevel": "상세 수준",
    "profile.tone": "톤",
    "profile.language": "언어",
    "profile.confidence": "프로필 신뢰도",
    "style.preview": "스타일 미리보기",
    "style.dimensions": "차원",
    "style.applying": "적용 중...",
    "style.applyStyle": "스타일 적용",
    "style.reset": "초기화",
    "style.original": "원본",
    "style.styled": "스타일 적용됨",
    "style.stats": "스타일 통계",
    "style.totalProfiles": "총 프로필",
    "style.totalSamples": "총 샘플",
    "gateway.connectedTools": "연결된 도구",
    "skills.marketplace.convertToWorkflow": "워크플로로 변환",
    "skills.marketplace.skillsMdNotFound": "SKILL.md를 찾을 수 없음 (main 또는 master 브랜치에 없음)",
    "skills.marketplace.skillsMdFetchFailed": "SKILL.md 가져오기 실패",
    "skills.sortPopular": "인기순",
    "skills.sortLatest": "최신순",
    "skills.sortStars": "스타순",
    "skills.update": "업데이트",
    "skills.createTitle": "새 스킬 만들기",
    "skills.create": "만들기",
    "skills.editTitle": "스킬 편집: {{name}}",
    "skills.edit": "편집",
    "skills.patchTitle": "스킬 패치: {{name}}",
    "skills.patch": "패치",
    "skills.name": "스킬 이름",
    "skills.namePlaceholder": "예: deploy-to-aws",
    "skills.nameRequired": "스킬 이름이 필요합니다",
    "skills.description": "설명",
    "skills.descriptionPlaceholder": "이 스킬이 하는 일에 대한 간단한 설명",
    "skills.content": "스킬 지침 (Markdown)",
    "skills.contentPlaceholder": "# 내 스킬\n\n## 개요\n이 스킬이 하는 일을 설명하세요...\n\n## 단계\n1. 1단계\n2. 2단계\n...",
    "skills.contentRequired": "스킬 내용이 필요합니다",
    "skills.patchPlaceholder": "문제와 수정 사항을 설명하세요...",
    "skills.editPlaceholder": "전체 스킬 본문 작성 (프론트매터는 유지됩니다)...",
    "skills.loadMore": "더 보기",
    "skills.proposal.title": "스킬 제안",
    "skills.proposal.empty": "아직 스킬 제안이 없습니다. 복잡한 Agent 작업을 완료하여 제안을 생성하세요.",
    "skills.proposal.hint": "이 스킬은 성공적인 Agent 워크플로에서 자동 생성되었습니다. 검토하고 생성하여 유사한 작업을 자동화하세요.",
    "skills.proposal.successWorkflow": "성공한 워크플로",
    "skills.proposal.failedWorkflow": "실패한 워크플로",
    "skills.proposal.partialSuccess": "부분 성공",
    "skills.proposal.confidence": "신뢰도",
    "skills.proposal.viewContent": "제안된 내용 보기",
    "skills.proposal.create": "생성",
    "skills.proposal.dismiss": "무시",
    "skills.proposal.created": "스킬 '{{name}}' 생성됨",
    "skills.proposal.error": "스킬 생성 실패",
    "skills.extractAtomicSkills": "원자 스킬 추출",
    "skills.decomposeSuccess": "원자 스킬이 성공적으로 추출되었습니다",
    "agent.askUserSupplementPlaceholder": "추가 입력 (선택 사항)...",
    "agent.askUserSubmitted": "제출됨",
    "common.modeLabel": "모드",
    "common.openDirectory": "디렉토리 열기",
}

# === SPANISH (es.json) translations ===
es = {
    "nav.link": "Enlace",
    "chat.workspaceLocked": "El directorio del espacio de trabajo no se puede cambiar después de iniciar la conversación",
    "chat.agentInitFailed": "Error al inicializar la sesión del agente",
    "chat.switchAgentModeNoConversation": "Inicie una nueva conversación antes de cambiar al modo Agente",
    "chat.cancelled": "Cancelado",
    "chat.takePhoto": "Tomar foto",
    "chat.recordAudio": "Grabar audio",
    "chat.recordVideo": "Grabar video",
    "chat.switchModeShortcut": "Consejo: Presione Shift+Tab para cambiar rápidamente de modo",
    "chat.batchArchiveToKnowledgeBase": "Archivar en lote en la base de conocimiento",
    "chat.saveAsWorkflow": "Guardar como flujo de trabajo",
    "chat.selectOneConversation": "Seleccione una conversación",
    "chat.searchPastSessions": "Buscar sesiones anteriores",
    "chat.searchPastConversations": "Buscar en todas las conversaciones anteriores...",
    "chat.searchGo": "Ir",
    "chat.searchResults": "{{count}} resultado(s) en sesiones anteriores",
    "chat.searchNoResults": "Sin resultados aún. Presione Enter o Ir para buscar.",
    "chat.insightsMemory": "Insights y Memoria",
    "chat.learningInsights": "Insights de Aprendizaje",
    "chat.noInsights": "Sin insights aún. Se acumulan mientras interactúa.",
    "chat.flushToMemory": "Guardar en memoria a largo plazo:",
    "chat.closedLoop": "Bucle Cerrado",
    "chat.closedLoopLearning": "Aprendizaje de Bucle Cerrado",
    "chat.trajectories": "Trayectorias",
    "chat.successRate": "Tasa de Éxito",
    "chat.insights": "Insights",
    "chat.patterns": "Patrones",
    "chat.closedLoopRunning": "Ejecutando",
    "chat.closedLoopStopped": "Detenido",
    "chat.nudgesPending": "Nudges pendientes",
    "chat.pipeline": "Pipeline: Trayectoria → Patrón → RL → Nudge → Memoria/Habilidad",
    "chat.learnedPatterns": "Patrones Aprendidos",
    "chat.noPatternsYet": "Sin patrones aún. Emergen mientras interactúa entre sesiones.",
    "chat.noPatternsFilter": "Ningún patrón coincide con el filtro actual.",
    "chat.rlEngine": "Motor RL",
    "chat.success": "Éxito",
    "chat.quality": "Calidad",
    "chat.config": "Configuración",
    "chat.gamma": "γ (descuento)",
    "chat.lambda": "λ (TD)",
    "chat.rewardScale": "Escala",
    "chat.entropyCoeff": "Coef. entropía",
    "chat.rewardWeights.task_completion": "finalización de tarea",
    "chat.rewardWeights.tool_efficiency": "eficiencia de herramientas",
    "chat.rewardWeights.reasoning_quality": "calidad de razonamiento",
    "chat.rewardWeights.error_recovery": "recuperación de errores",
    "chat.rewardWeights.user_feedback": "retroalimentación del usuario",
    "chat.rewardWeights.pattern_match": "coincidencia de patrón",
    "chat.exportTrainingData": "Exportar Datos de Entrenamiento",
    "chat.evolution": "Evolución",
    "chat.skillEvolution": "Evolución de Habilidades",
    "chat.generation": "Generación",
    "chat.bestFitness": "Mejor Aptitud",
    "chat.status": "Estado",
    "chat.converged": "Convergido",
    "chat.running": "Ejecutando",
    "chat.idle": "Inactivo",
    "chat.fitnessCurve": "Curva de Aptitud",
    "chat.improved": "Mejorado",
    "chat.noImprovement": "Sin mejora",
    "chat.profile": "Perfil",
    "chat.userProfile": "Perfil de Usuario",
    "chat.style": "Estilo",
    "chat.preferences": "Preferencias",
    "chat.expertise": "Experiencia",
    "chat.adaptingFromInteractions": "Adaptándose desde las interacciones...",
    "chat.rewindConversation": "Rebobinar Conversación",
    "chat.rewindConfirmContent": "Esto eliminará todos los mensajes después de este punto. Esta acción no se puede deshacer.",
    "chat.rewind": "Rebobinar",
    "chat.workflow.knowledgeExtract.name": "Extracción de Conocimiento de Negocio",
    "chat.workflow.knowledgeExtract.description": "Extraer conocimiento de negocio independiente del lenguaje del código para refactorización entre lenguajes.",
    "chat.workflow.knowledgeToCode.name": "De Conocimiento a Código",
    "chat.workflow.knowledgeToCode.description": "Generar implementación de código completa en el lenguaje objetivo desde la base de conocimiento de negocio, soportando migración entre lenguajes.",
    "chat.workflow.collectInputs.name": "Recopilar Entradas del Usuario",
    "chat.workflow.collectInputs.description": "Recopilar lenguaje objetivo, framework, ID de base de conocimiento, directorio de salida y otra información del proyecto.",
    "chat.workflow.decompositionSaved": "Flujo de trabajo de descomposición guardado exitosamente",
    "chat.workflow.semanticCheckTitle": "Habilidades Similares Encontradas",
    "chat.workflow.semanticCheckDescription": "Las siguientes habilidades atómicas generadas tienen alta similitud semántica con habilidades existentes. Puede usar la habilidad existente o mantener la generada.",
    "chat.workflow.semanticCheckApplied": "Reemplazo de habilidad aplicado",
    "chat.workflow.skipSemanticCheck": "Omitir",
    "chat.workflow.applySemanticCheck": "Aplicar",
    "chat.workflow.replaceWithExisting": "Usar Existente",
    "chat.workflow.keepGeneratedSkill": "Mantener Generada",
    "chat.workflow.upgradeExisting": "Actualizar Existente",
    "chat.workflow.existingSkill": "Habilidad Existente",
    "chat.workflow.matchReasons": "Razones de Coincidencia",
    "chat.workflow.generatedSkill": "Habilidad Generada",
    "chat.workflow.upgradeSkillTitle": "Actualizar Habilidad",
    "chat.workflow.upgradeSuggestion": "Sugerencia de Actualización LLM",
    "chat.workflow.generatingUpgrade": "Generando sugerencia de actualización...",
    "chat.workflow.applyUpgrade": "Aplicar Actualización",
    "chat.workflow.upgradeError": "Error al obtener la sugerencia de actualización",
    "chat.workflow.upgradedName": "Nombre Actualizado",
    "chat.workflow.inputSchema": "Esquema de Entrada",
    "chat.workflow.outputSchema": "Esquema de Salida",
    "chat.workflow.upgradeReasoning": "Razonamiento de Actualización",
    "gateway.connectedTools": "Herramientas Conectadas",
    "settings.storage.changeDir": "Cambiar Directorio",
    "settings.storage.resetDir": "Restablecer Predeterminado",
    "settings.storage.defaultDir": "Ubicación Predeterminada",
    "settings.storage.currentDir": "Directorio de Almacenamiento Actual",
    "settings.storage.changeDirTitle": "Cambiar Directorio de Almacenamiento",
    "settings.storage.changeDirConfirm": "¿Confirmar el cambio del directorio de almacenamiento a esta ubicación?",
    "settings.storage.changeDirNotEmpty": "El directorio de destino no está vacío. Continuar puede mezclarse con archivos existentes.",
    "settings.storage.migratePrompt": "¿Migrar archivos existentes al nuevo directorio?",
    "settings.storage.migrateYes": "Migrar Archivos",
    "settings.storage.migrateNo": "No Migrar",
    "settings.storage.migrating": "Migrando archivos...",
    "settings.storage.changeDirSuccess": "Directorio de almacenamiento cambiado",
    "settings.storage.changeDirSuccessMigrate": "Directorio de almacenamiento cambiado, {{count}} archivos migrados",
    "settings.storage.changeDirFailed": "Error al cambiar el directorio de almacenamiento",
    "settings.storage.resetDirConfirm": "¿Confirmar el restablecimiento a la ubicación de almacenamiento predeterminada?",
    "settings.storage.resetDirSuccess": "Restablecido a la ubicación de almacenamiento predeterminada",
    "settings.storage.dirNotWritable": "El directorio de destino no tiene permisos de escritura",
    "settings.storage.restartRequired": "Los cambios tendrán efecto completo después de reiniciar",
    "settings.storage.restartNow": "Reiniciar Ahora",
    "settings.storage.restartLater": "Reiniciar Después",
}

# Deep copy es translations to also apply to scheduler, localTools, tools, etc.
_es_common_english = {
    "settings.scheduler.customTasks": "Tareas Personalizadas",
    "settings.scheduler.addTask": "Añadir Tarea",
    "settings.scheduler.editTask": "Editar Tarea",
    "settings.scheduler.taskName": "Nombre de la Tarea",
    "settings.scheduler.taskDescription": "Descripción",
    "settings.scheduler.intervalHours": "Intervalo (horas)",
    "settings.scheduler.nextRunAt": "Próxima Ejecución",
    "settings.scheduler.lastRunAt": "Última Ejecución",
    "settings.scheduler.noTasks": "No hay tareas personalizadas configuradas",
    "settings.scheduler.createTask": "Crear Tarea",
    "settings.scheduler.updateTask": "Actualizar Tarea",
    "settings.scheduler.deleteTask": "Eliminar Tarea",
    "settings.scheduler.deleteTaskConfirm": "¿Eliminar esta tarea?",
    "settings.scheduler.pauseTask": "Pausar",
    "settings.scheduler.resumeTask": "Reanudar",
    "settings.scheduler.taskActive": "Activa",
    "settings.scheduler.taskPaused": "Pausada",
    "settings.scheduler.taskDisabled": "Deshabilitada",
    "settings.scheduler.selectInterval": "Seleccionar intervalo",
    "settings.scheduler.once": "Una vez",
    "settings.scheduler.daily": "Diario",
    "settings.scheduler.weekly": "Semanal",
    "settings.scheduler.monthly": "Mensual",
    "settings.scheduler.schedule": "Programación",
    "settings.scheduler.scheduleSettings": "Configuración de Programación",
    "settings.scheduler.scheduleType": "Tipo de Programación",
    "settings.scheduler.selectScheduleType": "Seleccionar tipo de programación",
    "settings.scheduler.scheduleInterval": "Intervalo",
    "settings.scheduler.scheduleDaily": "Diario",
    "settings.scheduler.scheduleWeekly": "Semanal",
    "settings.scheduler.scheduleMonthly": "Mensual",
    "settings.scheduler.scheduleAdvanced": "Avanzado",
    "settings.scheduler.weekdays": "Días de la semana",
    "settings.scheduler.monday": "Lun",
    "settings.scheduler.tuesday": "Mar",
    "settings.scheduler.wednesday": "Mié",
    "settings.scheduler.thursday": "Jue",
    "settings.scheduler.friday": "Vie",
    "settings.scheduler.saturday": "Sáb",
    "settings.scheduler.sunday": "Dom",
    "settings.scheduler.timeRanges": "Rangos de Tiempo",
    "settings.scheduler.startTime": "Inicio",
    "settings.scheduler.endTime": "Fin",
    "settings.scheduler.addTimeRange": "Añadir Rango de Tiempo",
    "settings.scheduler.monthDay": "Día del Mes",
    "settings.scheduler.dayOfMonth": "Día {{day}}",
    "settings.scheduler.selectDayOfMonth": "Seleccionar día del mes",
    "settings.scheduler.excludeHolidays": "Excluir festivos",
    "settings.scheduler.excludeCustomDates": "Excluir Fechas Personalizadas",
    "settings.scheduler.enterExcludeDates": "Ingrese fechas a excluir (AAAA-MM-DD)",
    "settings.scheduler.intervalDesc": "Cada {{hours}} horas",
    "settings.scheduler.dailyDesc": "Diario",
    "settings.scheduler.weeklyDesc": "Semanal los {{days}}",
    "settings.scheduler.monthlyDesc": "Mensual el día {{day}}",
    "settings.scheduler.advancedDesc": "Programación avanzada",
    "settings.scheduler.selectTemplate": "Seleccionar Plantilla",
    "settings.scheduler.workflowTemplates": "Plantillas de Flujo de Trabajo",
    "settings.scheduler.reportTemplates": "Plantillas de Informes",
    "settings.scheduler.workflowCodeReview": "Flujo de Revisión de Código",
    "settings.scheduler.workflowBugFix": "Flujo de Corrección de Errores",
    "settings.scheduler.workflowDocGen": "Flujo de Documentación",
    "settings.scheduler.workflowTestGen": "Flujo de Generación de Pruebas",
    "settings.scheduler.workflowRefactor": "Flujo de Refactorización",
    "settings.scheduler.workflowExplore": "Flujo de Exploración de Código",
    "settings.scheduler.workflowPerformance": "Flujo de Optimización de Rendimiento",
    "settings.scheduler.workflowKnowledgeExtract": "Flujo de Extracción de Conocimiento",
    "settings.scheduler.workflowKnowledgeToCode": "Flujo de Conocimiento a Código",
    "settings.localTools.title": "Herramientas Locales",
    "settings.localTools.description": "Administrar el estado de habilitación/deshabilitación de herramientas integradas. Las herramientas deshabilitadas no aparecerán en la lista de herramientas disponibles del Agente.",
    "settings.localTools.groupFetch": "Búsqueda Web",
    "settings.localTools.groupSearchFile": "Búsqueda de Archivos",
    "settings.localTools.groupFilesystem": "Sistema de Archivos",
    "settings.localTools.groupSystem": "Comandos del Sistema",
    "settings.localTools.groupSearch": "Búsqueda Web",
    "settings.localTools.groupKnowledge": "Base de Conocimiento",
    "settings.localTools.groupStorage": "Almacenamiento de Objetos",
    "settings.localTools.groupSkills": "Gestión de Habilidades",
    "settings.localTools.groupSession": "Búsqueda de Sesiones",
    "settings.localTools.groupMemory": "Gestión de Memoria",
    "settings.tools.title": "Administrador de Herramientas",
    "settings.tools.tabBuiltin": "Herramientas Integradas",
    "settings.tools.tabMcp": "Servidores MCP",
    "settings.tools.tabGenerated": "Herramientas Generadas",
    "settings.tools.tabSemantic": "Verificación Semántica",
    "settings.generatedTools.title": "Herramientas Generadas",
    "settings.generatedTools.description": "Herramientas de plantilla de instrucciones generadas a partir de la descomposición de habilidades compuestas. Estas herramientas usan LLM para ejecutar instrucciones y simular funcionalidad.",
    "settings.generatedTools.toolName": "Nombre de la Herramienta",
    "settings.generatedTools.originalName": "Nombre Original",
    "settings.generatedTools.createdAt": "Creado En",
    "settings.generatedTools.deleteConfirm": "¿Eliminar esta herramienta generada?",
    "settings.generatedTools.deleteSuccess": "Eliminado exitosamente",
    "settings.generatedTools.total": "{{count}} herramienta(s) generada(s)",
    "settings.generatedTools.empty": "Sin herramientas generadas",
    "settings.toolSemanticCheck.title": "Verificación Semántica de Herramientas",
    "settings.toolSemanticCheck.description": "Encontrar herramientas similares y actualizar las existentes usando IA",
    "settings.toolSemanticCheck.searchPlaceholder": "Ingrese nombre o descripción de la herramienta",
    "settings.toolSemanticCheck.emptySearch": "Ingrese un término de búsqueda",
    "settings.toolSemanticCheck.noMatches": "No se encontraron herramientas similares",
    "settings.toolSemanticCheck.empty": "Ingrese un término de búsqueda para encontrar herramientas similares",
    "settings.toolSemanticCheck.matches": "{{count}} coincidencias",
    "settings.toolSemanticCheck.checkingTool": "Buscando herramientas similares a {{tool}}",
    "settings.toolSemanticCheck.similarity": "Similitud",
    "settings.toolSemanticCheck.upgrade": "Actualizar",
    "settings.toolSemanticCheck.upgradeModalTitle": "Actualizar Herramienta",
    "settings.toolSemanticCheck.existingTool": "Herramienta Existente",
    "settings.toolSemanticCheck.generatedTool": "Herramienta Generada",
    "settings.toolSemanticCheck.toolType": "Tipo de Herramienta",
    "settings.toolSemanticCheck.noDescription": "Sin descripción",
    "settings.toolSemanticCheck.performUpgrade": "Realizar Actualización",
    "settings.toolSemanticCheck.upgradeSuccess": "Sugerencia de actualización de herramienta generada",
    "settings.toolSemanticCheck.upgradeSuggestion": "Sugerencia de Actualización",
    "settings.toolSemanticCheck.reasoning": "Razonamiento",
    "settings.groupWorkspace": "Espacio de Trabajo",
    "settings.defaultWorkspaceDir": "Directorio de Espacio de Trabajo Predeterminado",
    "settings.userProfile.title": "Perfil de Usuario",
    "settings.userProfile.overview": "Resumen del Perfil",
    "settings.userProfile.userId": "ID de Usuario",
    "settings.userProfile.lastUpdated": "Última Actualización",
    "settings.userProfile.codingStyle": "Estilo de Codificación",
    "settings.userProfile.namingConvention": "Convención de Nombres",
    "settings.userProfile.indentationStyle": "Estilo de Indentación",
    "settings.userProfile.commentStyle": "Estilo de Comentarios",
    "settings.userProfile.communication": "Comunicación",
    "settings.userProfile.detailLevel": "Nivel de Detalle",
    "settings.userProfile.tone": "Tono",
    "settings.userProfile.language": "Idioma",
    "settings.userProfile.confidence": "Confianza del Perfil",
    "settings.userProfile.loading": "Cargando perfil...",
    "link.title": "Enlace",
    "link.searchGateways": "Buscar pasarelas",
    "link.noGateways": "Sin conexiones de pasarela",
    "link.selectGateway": "Seleccionar una conexión de pasarela",
    "link.addGateway": "Añadir Conexión de Pasarela",
    "link.gatewayName": "Nombre de la Conexión",
    "link.gatewayType": "Tipo de Pasarela",
    "link.endpoint": "Endpoint",
    "link.apiKey": "Clave API",
    "link.apiKeyPlaceholder": "Opcional, dejar vacío para sin clave",
    "link.namePlaceholder": "ej. OpenClaw-Prod",
    "link.nameRequired": "Ingrese un nombre de conexión",
    "link.endpointRequired": "Ingrese un endpoint",
    "link.addSuccess": "Conexión de pasarela añadida",
    "link.addFailed": "Error al añadir la conexión de pasarela",
    "link.deleteSuccess": "Conexión de pasarela eliminada",
    "link.deleteFailed": "Error al eliminar la conexión de pasarela",
    "link.deleteConfirm": "¿Está seguro de que desea eliminar esta conexión de pasarela?",
    "link.typeCustom": "Personalizado",
    "link.statusConnected": "Conectado",
    "link.statusDisconnected": "Desconectado",
    "link.statusConnecting": "Conectando",
    "link.statusError": "Error",
    "link.connect": "Conectar",
    "link.disconnect": "Desconectar",
    "link.latency": "Latencia",
    "link.overview": "Resumen",
    "link.models": "Modelos",
    "link.skills": "Habilidades",
    "link.policies": "Políticas",
    "link.newConversation": "Nueva Conversación",
    "link.syncedModels": "Modelos Sincronizados",
    "link.syncedSkills": "Habilidades Sincronizadas",
    "link.lastSync": "Última Sincronización",
    "link.recentActivity": "Actividad Reciente",
    "link.noActivity": "Sin actividad aún",
    "link.autoSyncModels": "Sincronización automática de modelos",
    "link.autoSyncSkills": "Sincronización automática de habilidades",
    "link.syncAllModels": "Sincronizar Todos los Modelos",
    "link.syncAllSkills": "Sincronizar Todas las Habilidades",
    "link.syncAllSuccess": "Sincronización exitosa",
    "link.syncAllFailed": "Error de sincronización",
    "link.pushModelsSuccess": "Modelos enviados exitosamente",
    "link.pushModelsFailed": "Error al enviar modelos",
    "link.pushSkillsSuccess": "Habilidades enviadas exitosamente",
    "link.pushSkillsFailed": "Error al enviar habilidades",
    "link.modelName": "Nombre del Modelo",
    "link.providerName": "Proveedor",
    "link.syncStatus": "Estado de Sincronización",
    "link.syncStatusSynced": "Sincronizado",
    "link.syncStatusPending": "Pendiente",
    "link.syncStatusFailed": "Fallido",
    "link.syncStatusNotSelected": "No Seleccionado",
    "link.skillName": "Nombre de la Habilidad",
    "link.skillVersion": "Versión",
    "link.noModels": "Sin registros de sincronización de modelos",
    "link.noSkills": "Sin registros de sincronización de habilidades",
    "link.push": "Enviar",
    "link.routingPolicy": "Política de Enrutamiento",
    "link.routeStrategy": "Estrategia de Ruta",
    "link.roundRobin": "Round Robin",
    "link.leastLatency": "Menor Latencia",
    "link.weighted": "Ponderado",
    "link.modelFallback": "Respaldo de Modelo",
    "link.rateLimiting": "Limitación de Velocidad",
    "link.globalRpm": "RPM Global",
    "link.perModelRpm": "RPM por Modelo",
    "link.tokenLimitPerMinute": "Límite de Tokens por Minuto",
    "link.unlimited": "Ilimitado",
    "link.keyManagement": "Gestión de Claves",
    "link.keyRotation": "Rotación de Claves",
    "link.sequential": "Secuencial",
    "link.random": "Aleatorio",
    "link.keyFailover": "Conmutación por Error de Clave",
    "link.savePolicy": "Guardar Política",
    "link.policySaved": "Política guardada",
    "link.policySaveFailed": "Error al guardar la política",
    "link.noPolicy": "Sin política configurada",
    "link.loadPolicy": "Cargar Política",
    "profile.loading": "Cargando perfil...",
    "profile.overview": "Resumen del Perfil",
    "profile.userId": "ID de Usuario",
    "profile.lastUpdated": "Última Actualización",
    "profile.codingStyle": "Estilo de Codificación",
    "profile.namingConvention": "Convención de Nombres",
    "profile.indentationStyle": "Estilo de Indentación",
    "profile.commentStyle": "Estilo de Comentarios",
    "profile.communication": "Comunicación",
    "profile.detailLevel": "Nivel de Detalle",
    "profile.tone": "Tono",
    "profile.language": "Idioma",
    "profile.confidence": "Confianza del Perfil",
    "style.preview": "Vista Previa de Estilo",
    "style.dimensions": "Dimensiones",
    "style.applying": "Aplicando...",
    "style.applyStyle": "Aplicar Estilo",
    "style.reset": "Restablecer",
    "style.original": "Original",
    "style.styled": "Estilizado",
    "style.stats": "Estadísticas de Estilo",
    "style.totalProfiles": "Perfiles Totales",
    "style.totalSamples": "Muestras Totales",
    "skills.marketplace.convertToWorkflow": "Convertir a Flujo de Trabajo",
    "skills.marketplace.skillsMdNotFound": "SKILL.md no encontrado (no se encuentra en la rama main o master)",
    "skills.marketplace.skillsMdFetchFailed": "Error al obtener SKILL.md",
    "skills.sortPopular": "Popular",
    "skills.sortLatest": "Más Reciente",
    "skills.sortStars": "Estrellas",
    "skills.update": "Actualizar",
    "skills.createTitle": "Crear Nueva Habilidad",
    "skills.create": "Crear",
    "skills.editTitle": "Editar Habilidad: {{name}}",
    "skills.edit": "Editar",
    "skills.patchTitle": "Parchear Habilidad: {{name}}",
    "skills.patch": "Parchear",
    "skills.name": "Nombre de la Habilidad",
    "skills.namePlaceholder": "ej. deploy-to-aws",
    "skills.nameRequired": "El nombre de la habilidad es obligatorio",
    "skills.description": "Descripción",
    "skills.descriptionPlaceholder": "Breve descripción de lo que hace esta habilidad",
    "skills.content": "Instrucciones de la Habilidad (Markdown)",
    "skills.contentPlaceholder": "# Mi Habilidad\n\n## Resumen\nDescriba lo que hace esta habilidad...\n\n## Pasos\n1. Paso uno\n2. Paso dos\n...",
    "skills.contentRequired": "El contenido de la habilidad es obligatorio",
    "skills.patchPlaceholder": "Describa el problema y la solución...",
    "skills.editPlaceholder": "Escriba el cuerpo completo de la habilidad (el frontmatter se conservará)...",
    "skills.loadMore": "Cargar Más",
    "skills.proposal.title": "Propuestas de Habilidades",
    "skills.proposal.empty": "Sin propuestas de habilidades aún. Complete tareas complejas del Agente para generar sugerencias.",
    "skills.proposal.hint": "Estas habilidades se generaron automáticamente a partir de sus flujos de trabajo exitosos del Agente. Revíselas y créelas para automatizar tareas similares.",
    "skills.proposal.successWorkflow": "Flujo de Trabajo Exitoso",
    "skills.proposal.failedWorkflow": "Flujo de Trabajo Fallido",
    "skills.proposal.partialSuccess": "Éxito Parcial",
    "skills.proposal.confidence": "confianza",
    "skills.proposal.viewContent": "Ver contenido sugerido",
    "skills.proposal.create": "Crear",
    "skills.proposal.dismiss": "Descartar",
    "skills.proposal.created": "Habilidad '{{name}}' creada",
    "skills.proposal.error": "Error al crear la habilidad",
    "skills.extractAtomicSkills": "Extraer Habilidades Atómicas",
    "skills.decomposeSuccess": "Habilidades atómicas extraídas exitosamente",
    "agent.askUserSupplementPlaceholder": "Entrada adicional (opcional)...",
    "agent.askUserSubmitted": "Enviado",
    "common.modeLabel": "Modo",
    "common.openDirectory": "Abrir Directorio",
}

es.update(_es_common_english)

# === FRENCH (fr.json) translations ===
fr = {
    "nav.link": "Lien",
    "chat.workspaceLocked": "Le répertoire de l'espace de travail ne peut pas être modifié après le début de la conversation",
    "chat.agentInitFailed": "Échec de l'initialisation de la session de l'agent",
    "chat.switchAgentModeNoConversation": "Veuillez d'abord démarrer une nouvelle conversation avant de passer en mode Agent",
    "chat.cancelled": "Annulé",
    "chat.takePhoto": "Prendre une photo",
    "chat.recordAudio": "Enregistrer l'audio",
    "chat.recordVideo": "Enregistrer une vidéo",
    "chat.switchModeShortcut": "Astuce : Appuyez sur Maj+Tab pour changer rapidement de mode",
    "chat.batchArchiveToKnowledgeBase": "Archiver par lot dans la base de connaissances",
    "chat.saveAsWorkflow": "Enregistrer comme workflow",
    "chat.selectOneConversation": "Veuillez sélectionner une conversation",
    "chat.searchPastSessions": "Rechercher les sessions passées",
    "chat.searchPastConversations": "Rechercher dans toutes les conversations passées...",
    "chat.searchGo": "Aller",
    "chat.searchResults": "{{count}} résultat(s) dans les sessions passées",
    "chat.searchNoResults": "Aucun résultat pour l'instant. Appuyez sur Entrée ou Aller pour rechercher.",
    "chat.insightsMemory": "Aperçus et Mémoire",
    "chat.learningInsights": "Aperçus d'Apprentissage",
    "chat.noInsights": "Pas encore d'aperçus. Ils s'accumulent au fil de vos interactions.",
    "chat.flushToMemory": "Sauvegarder en mémoire à long terme :",
    "chat.closedLoop": "Boucle Fermée",
    "chat.closedLoopLearning": "Apprentissage en Boucle Fermée",
    "chat.trajectories": "Trajectoires",
    "chat.successRate": "Taux de Réussite",
    "chat.insights": "Aperçus",
    "chat.patterns": "Modèles",
    "chat.closedLoopRunning": "En cours",
    "chat.closedLoopStopped": "Arrêté",
    "chat.nudgesPending": "Nudges en attente",
    "chat.pipeline": "Pipeline : Trajectoire → Modèle → RL → Nudge → Mémoire/Compétence",
    "chat.learnedPatterns": "Modèles Appris",
    "chat.noPatternsYet": "Pas encore de modèles. Ils émergent au fil de vos interactions entre sessions.",
    "chat.noPatternsFilter": "Aucun modèle ne correspond au filtre actuel.",
    "chat.rlEngine": "Moteur RL",
    "chat.success": "Succès",
    "chat.quality": "Qualité",
    "chat.config": "Configuration",
    "chat.gamma": "γ (remise)",
    "chat.lambda": "λ (TD)",
    "chat.rewardScale": "Échelle",
    "chat.entropyCoeff": "Coef. entropie",
    "chat.rewardWeights.task_completion": "achèvement de la tâche",
    "chat.rewardWeights.tool_efficiency": "efficacité des outils",
    "chat.rewardWeights.reasoning_quality": "qualité du raisonnement",
    "chat.rewardWeights.error_recovery": "récupération d'erreur",
    "chat.rewardWeights.user_feedback": "retour utilisateur",
    "chat.rewardWeights.pattern_match": "correspondance de motif",
    "chat.exportTrainingData": "Exporter les Données d'Entraînement",
    "chat.evolution": "Évolution",
    "chat.skillEvolution": "Évolution des Compétences",
    "chat.generation": "Génération",
    "chat.bestFitness": "Meilleure Aptitude",
    "chat.status": "Statut",
    "chat.converged": "Convergé",
    "chat.running": "En cours",
    "chat.idle": "Inactif",
    "chat.fitnessCurve": "Courbe d'Aptitude",
    "chat.improved": "Amélioré",
    "chat.noImprovement": "Aucune amélioration",
    "chat.profile": "Profil",
    "chat.userProfile": "Profil Utilisateur",
    "chat.style": "Style",
    "chat.preferences": "Préférences",
    "chat.expertise": "Expertise",
    "chat.adaptingFromInteractions": "Adaptation à partir des interactions...",
    "chat.rewindConversation": "Rembobiner la Conversation",
    "chat.rewindConfirmContent": "Cela supprimera tous les messages après ce point. Cette action est irréversible.",
    "chat.rewind": "Rembobiner",
    "chat.workflow.knowledgeExtract.name": "Extraction de Connaissances Métier",
    "chat.workflow.knowledgeExtract.description": "Extraire des connaissances métier indépendantes du langage à partir du code pour la refactorisation inter-langages.",
    "chat.workflow.knowledgeToCode.name": "De la Connaissance au Code",
    "chat.workflow.knowledgeToCode.description": "Générer une implémentation de code complète dans le langage cible à partir de la base de connaissances métier, prenant en charge la migration inter-langages.",
    "chat.workflow.collectInputs.name": "Collecter les Entrées Utilisateur",
    "chat.workflow.collectInputs.description": "Collecter le langage cible, le framework, l'ID de la base de connaissances, le répertoire de sortie et d'autres informations du projet.",
    "chat.workflow.decompositionSaved": "Workflow de décomposition enregistré avec succès",
    "chat.workflow.semanticCheckTitle": "Compétences Similaires Trouvées",
    "chat.workflow.semanticCheckDescription": "Les compétences atomiques générées suivantes ont une forte similarité sémantique avec des compétences existantes. Vous pouvez utiliser la compétence existante ou conserver celle générée.",
    "chat.workflow.semanticCheckApplied": "Remplacement de compétence appliqué",
    "chat.workflow.skipSemanticCheck": "Ignorer",
    "chat.workflow.applySemanticCheck": "Appliquer",
    "chat.workflow.replaceWithExisting": "Utiliser l'Existante",
    "chat.workflow.keepGeneratedSkill": "Conserver la Générée",
    "chat.workflow.upgradeExisting": "Mettre à Niveau l'Existante",
    "chat.workflow.existingSkill": "Compétence Existante",
    "chat.workflow.matchReasons": "Raisons de Correspondance",
    "chat.workflow.generatedSkill": "Compétence Générée",
    "chat.workflow.upgradeSkillTitle": "Mettre à Niveau la Compétence",
    "chat.workflow.upgradeSuggestion": "Suggestion de Mise à Niveau LLM",
    "chat.workflow.generatingUpgrade": "Génération de la suggestion de mise à niveau...",
    "chat.workflow.applyUpgrade": "Appliquer la Mise à Niveau",
    "chat.workflow.upgradeError": "Échec de l'obtention de la suggestion de mise à niveau",
    "chat.workflow.upgradedName": "Nom Mis à Niveau",
    "chat.workflow.inputSchema": "Schéma d'Entrée",
    "chat.workflow.outputSchema": "Schéma de Sortie",
    "chat.workflow.upgradeReasoning": "Raisonnement de Mise à Niveau",
    "gateway.connectedTools": "Outils Connectés",
    "settings.storage.changeDir": "Changer le Répertoire",
    "settings.storage.resetDir": "Réinitialiser par Défaut",
    "settings.storage.defaultDir": "Emplacement par Défaut",
    "settings.storage.currentDir": "Répertoire de Stockage Actuel",
    "settings.storage.changeDirTitle": "Changer le Répertoire de Stockage",
    "settings.storage.changeDirConfirm": "Confirmer le changement du répertoire de stockage vers cet emplacement ?",
    "settings.storage.changeDirNotEmpty": "Le répertoire cible n'est pas vide. Continuer peut mélanger avec les fichiers existants.",
    "settings.storage.migratePrompt": "Migrer les fichiers existants vers le nouveau répertoire ?",
    "settings.storage.migrateYes": "Migrer les Fichiers",
    "settings.storage.migrateNo": "Ne Pas Migrer",
    "settings.storage.migrating": "Migration des fichiers...",
    "settings.storage.changeDirSuccess": "Répertoire de stockage changé",
    "settings.storage.changeDirSuccessMigrate": "Répertoire de stockage changé, {{count}} fichiers migrés",
    "settings.storage.changeDirFailed": "Échec du changement du répertoire de stockage",
    "settings.storage.resetDirConfirm": "Confirmer la réinitialisation vers l'emplacement de stockage par défaut ?",
    "settings.storage.resetDirSuccess": "Réinitialisé vers l'emplacement de stockage par défaut",
    "settings.storage.dirNotWritable": "Le répertoire cible n'est pas accessible en écriture",
    "settings.storage.restartRequired": "Les modifications prendront pleinement effet après le redémarrage",
    "settings.storage.restartNow": "Redémarrer Maintenant",
    "settings.storage.restartLater": "Redémarrer Plus Tard",
}

_fr_common_english = {
    "settings.scheduler.customTasks": "Tâches Personnalisées",
    "settings.scheduler.addTask": "Ajouter une Tâche",
    "settings.scheduler.editTask": "Modifier la Tâche",
    "settings.scheduler.taskName": "Nom de la Tâche",
    "settings.scheduler.taskDescription": "Description",
    "settings.scheduler.intervalHours": "Intervalle (heures)",
    "settings.scheduler.nextRunAt": "Prochaine Exécution",
    "settings.scheduler.lastRunAt": "Dernière Exécution",
    "settings.scheduler.noTasks": "Aucune tâche personnalisée configurée",
    "settings.scheduler.createTask": "Créer une Tâche",
    "settings.scheduler.updateTask": "Mettre à Jour la Tâche",
    "settings.scheduler.deleteTask": "Supprimer la Tâche",
    "settings.scheduler.deleteTaskConfirm": "Supprimer cette tâche ?",
    "settings.scheduler.pauseTask": "Pause",
    "settings.scheduler.resumeTask": "Reprendre",
    "settings.scheduler.taskActive": "Active",
    "settings.scheduler.taskPaused": "En Pause",
    "settings.scheduler.taskDisabled": "Désactivée",
    "settings.scheduler.selectInterval": "Sélectionner l'intervalle",
    "settings.scheduler.once": "Une fois",
    "settings.scheduler.daily": "Quotidien",
    "settings.scheduler.weekly": "Hebdomadaire",
    "settings.scheduler.monthly": "Mensuel",
    "settings.scheduler.schedule": "Planification",
    "settings.scheduler.scheduleSettings": "Paramètres de Planification",
    "settings.scheduler.scheduleType": "Type de Planification",
    "settings.scheduler.selectScheduleType": "Sélectionner le type de planification",
    "settings.scheduler.scheduleInterval": "Intervalle",
    "settings.scheduler.scheduleDaily": "Quotidien",
    "settings.scheduler.scheduleWeekly": "Hebdomadaire",
    "settings.scheduler.scheduleMonthly": "Mensuel",
    "settings.scheduler.scheduleAdvanced": "Avancé",
    "settings.scheduler.weekdays": "Jours de la Semaine",
    "settings.scheduler.monday": "Lun",
    "settings.scheduler.tuesday": "Mar",
    "settings.scheduler.wednesday": "Mer",
    "settings.scheduler.thursday": "Jeu",
    "settings.scheduler.friday": "Ven",
    "settings.scheduler.saturday": "Sam",
    "settings.scheduler.sunday": "Dim",
    "settings.scheduler.timeRanges": "Plages Horaires",
    "settings.scheduler.startTime": "Début",
    "settings.scheduler.endTime": "Fin",
    "settings.scheduler.addTimeRange": "Ajouter une Plage Horaire",
    "settings.scheduler.monthDay": "Jour du Mois",
    "settings.scheduler.dayOfMonth": "Jour {{day}}",
    "settings.scheduler.selectDayOfMonth": "Sélectionner le jour du mois",
    "settings.scheduler.excludeHolidays": "Exclure les jours fériés",
    "settings.scheduler.excludeCustomDates": "Exclure des Dates Personnalisées",
    "settings.scheduler.enterExcludeDates": "Entrer les dates à exclure (AAAA-MM-JJ)",
    "settings.scheduler.intervalDesc": "Toutes les {{hours}} heures",
    "settings.scheduler.dailyDesc": "Quotidien",
    "settings.scheduler.weeklyDesc": "Hebdomadaire le {{days}}",
    "settings.scheduler.monthlyDesc": "Mensuel le jour {{day}}",
    "settings.scheduler.advancedDesc": "Planification avancée",
    "settings.scheduler.selectTemplate": "Sélectionner un Modèle",
    "settings.scheduler.workflowTemplates": "Modèles de Workflow",
    "settings.scheduler.reportTemplates": "Modèles de Rapport",
    "settings.scheduler.workflowCodeReview": "Workflow de Revue de Code",
    "settings.scheduler.workflowBugFix": "Workflow de Correction de Bug",
    "settings.scheduler.workflowDocGen": "Workflow de Documentation",
    "settings.scheduler.workflowTestGen": "Workflow de Génération de Tests",
    "settings.scheduler.workflowRefactor": "Workflow de Refactorisation",
    "settings.scheduler.workflowExplore": "Workflow d'Exploration de Code",
    "settings.scheduler.workflowPerformance": "Workflow d'Optimisation de Performance",
    "settings.scheduler.workflowKnowledgeExtract": "Workflow d'Extraction de Connaissances",
    "settings.scheduler.workflowKnowledgeToCode": "Workflow de Connaissances vers Code",
    "settings.localTools.title": "Outils Locaux",
    "settings.localTools.description": "Gérer l'état d'activation/désactivation des outils intégrés. Les outils désactivés n'apparaîtront pas dans la liste des outils disponibles de l'Agent.",
    "settings.localTools.groupFetch": "Récupération Web",
    "settings.localTools.groupSearchFile": "Recherche de Fichiers",
    "settings.localTools.groupFilesystem": "Système de Fichiers",
    "settings.localTools.groupSystem": "Commandes Système",
    "settings.localTools.groupSearch": "Recherche Web",
    "settings.localTools.groupKnowledge": "Base de Connaissances",
    "settings.localTools.groupStorage": "Stockage d'Objets",
    "settings.localTools.groupSkills": "Gestion des Compétences",
    "settings.localTools.groupSession": "Recherche de Sessions",
    "settings.localTools.groupMemory": "Gestion de la Mémoire",
    "settings.tools.title": "Gestionnaire d'Outils",
    "settings.tools.tabBuiltin": "Outils Intégrés",
    "settings.tools.tabMcp": "Serveurs MCP",
    "settings.tools.tabGenerated": "Outils Générés",
    "settings.tools.tabSemantic": "Vérification Sémantique",
    "settings.generatedTools.title": "Outils Générés",
    "settings.generatedTools.description": "Outils de modèle d'invite générés à partir de la décomposition de compétences composites. Ces outils utilisent le LLM pour exécuter des invites et simuler des fonctionnalités.",
    "settings.generatedTools.toolName": "Nom de l'Outil",
    "settings.generatedTools.originalName": "Nom d'Origine",
    "settings.generatedTools.createdAt": "Créé Le",
    "settings.generatedTools.deleteConfirm": "Supprimer cet outil généré ?",
    "settings.generatedTools.deleteSuccess": "Supprimé avec succès",
    "settings.generatedTools.total": "{{count}} outil(s) généré(s)",
    "settings.generatedTools.empty": "Aucun outil généré",
    "settings.toolSemanticCheck.title": "Vérification Sémantique des Outils",
    "settings.toolSemanticCheck.description": "Trouver des outils similaires et mettre à niveau les existants en utilisant l'IA",
    "settings.toolSemanticCheck.searchPlaceholder": "Entrez le nom ou la description de l'outil",
    "settings.toolSemanticCheck.emptySearch": "Veuillez entrer un terme de recherche",
    "settings.toolSemanticCheck.noMatches": "Aucun outil similaire trouvé",
    "settings.toolSemanticCheck.empty": "Entrez un terme de recherche pour trouver des outils similaires",
    "settings.toolSemanticCheck.matches": "{{count}} correspondances",
    "settings.toolSemanticCheck.checkingTool": "Vérification des outils similaires à {{tool}}",
    "settings.toolSemanticCheck.similarity": "Similarité",
    "settings.toolSemanticCheck.upgrade": "Mettre à Niveau",
    "settings.toolSemanticCheck.upgradeModalTitle": "Mettre à Niveau l'Outil",
    "settings.toolSemanticCheck.existingTool": "Outil Existant",
    "settings.toolSemanticCheck.generatedTool": "Outil Généré",
    "settings.toolSemanticCheck.toolType": "Type d'Outil",
    "settings.toolSemanticCheck.noDescription": "Aucune description",
    "settings.toolSemanticCheck.performUpgrade": "Effectuer la Mise à Niveau",
    "settings.toolSemanticCheck.upgradeSuccess": "Suggestion de mise à niveau d'outil générée",
    "settings.toolSemanticCheck.upgradeSuggestion": "Suggestion de Mise à Niveau",
    "settings.toolSemanticCheck.reasoning": "Raisonnement",
    "settings.groupWorkspace": "Espace de Travail",
    "settings.defaultWorkspaceDir": "Répertoire de l'Espace de Travail par Défaut",
    "settings.userProfile.title": "Profil Utilisateur",
    "settings.userProfile.overview": "Aperçu du Profil",
    "settings.userProfile.userId": "ID Utilisateur",
    "settings.userProfile.lastUpdated": "Dernière Mise à Jour",
    "settings.userProfile.codingStyle": "Style de Codage",
    "settings.userProfile.namingConvention": "Convention de Nommage",
    "settings.userProfile.indentationStyle": "Style d'Indentation",
    "settings.userProfile.commentStyle": "Style de Commentaires",
    "settings.userProfile.communication": "Communication",
    "settings.userProfile.detailLevel": "Niveau de Détail",
    "settings.userProfile.tone": "Ton",
    "settings.userProfile.language": "Langue",
    "settings.userProfile.confidence": "Confiance du Profil",
    "settings.userProfile.loading": "Chargement du profil...",
    "link.title": "Lien",
    "link.searchGateways": "Rechercher des passerelles",
    "link.noGateways": "Aucune connexion de passerelle",
    "link.selectGateway": "Sélectionner une connexion de passerelle",
    "link.addGateway": "Ajouter une Connexion de Passerelle",
    "link.gatewayName": "Nom de la Connexion",
    "link.gatewayType": "Type de Passerelle",
    "link.endpoint": "Point de Terminaison",
    "link.apiKey": "Clé API",
    "link.apiKeyPlaceholder": "Optionnel, laisser vide pour aucune clé",
    "link.namePlaceholder": "ex. OpenClaw-Prod",
    "link.nameRequired": "Veuillez entrer un nom de connexion",
    "link.endpointRequired": "Veuillez entrer un point de terminaison",
    "link.addSuccess": "Connexion de passerelle ajoutée",
    "link.addFailed": "Échec de l'ajout de la connexion de passerelle",
    "link.deleteSuccess": "Connexion de passerelle supprimée",
    "link.deleteFailed": "Échec de la suppression de la connexion de passerelle",
    "link.deleteConfirm": "Êtes-vous sûr de vouloir supprimer cette connexion de passerelle ?",
    "link.typeCustom": "Personnalisé",
    "link.statusConnected": "Connecté",
    "link.statusDisconnected": "Déconnecté",
    "link.statusConnecting": "Connexion",
    "link.statusError": "Erreur",
    "link.connect": "Connecter",
    "link.disconnect": "Déconnecter",
    "link.latency": "Latence",
    "link.overview": "Vue d'Ensemble",
    "link.models": "Modèles",
    "link.skills": "Compétences",
    "link.policies": "Politiques",
    "link.newConversation": "Nouvelle Conversation",
    "link.syncedModels": "Modèles Synchronisés",
    "link.syncedSkills": "Compétences Synchronisées",
    "link.lastSync": "Dernière Synchronisation",
    "link.recentActivity": "Activité Récente",
    "link.noActivity": "Pas encore d'activité",
    "link.autoSyncModels": "Synchronisation automatique des modèles",
    "link.autoSyncSkills": "Synchronisation automatique des compétences",
    "link.syncAllModels": "Synchroniser Tous les Modèles",
    "link.syncAllSkills": "Synchroniser Toutes les Compétences",
    "link.syncAllSuccess": "Synchronisation réussie",
    "link.syncAllFailed": "Échec de la synchronisation",
    "link.pushModelsSuccess": "Modèles envoyés avec succès",
    "link.pushModelsFailed": "Échec de l'envoi des modèles",
    "link.pushSkillsSuccess": "Compétences envoyées avec succès",
    "link.pushSkillsFailed": "Échec de l'envoi des compétences",
    "link.modelName": "Nom du Modèle",
    "link.providerName": "Fournisseur",
    "link.syncStatus": "Statut de Synchronisation",
    "link.syncStatusSynced": "Synchronisé",
    "link.syncStatusPending": "En Attente",
    "link.syncStatusFailed": "Échec",
    "link.syncStatusNotSelected": "Non Sélectionné",
    "link.skillName": "Nom de la Compétence",
    "link.skillVersion": "Version",
    "link.noModels": "Aucun enregistrement de synchronisation de modèles",
    "link.noSkills": "Aucun enregistrement de synchronisation de compétences",
    "link.push": "Envoyer",
    "link.routingPolicy": "Politique de Routage",
    "link.routeStrategy": "Stratégie de Routage",
    "link.roundRobin": "Tourniquet",
    "link.leastLatency": "Latence Minimale",
    "link.weighted": "Pondéré",
    "link.modelFallback": "Modèle de Secours",
    "link.rateLimiting": "Limitation de Débit",
    "link.globalRpm": "RPM Global",
    "link.perModelRpm": "RPM par Modèle",
    "link.tokenLimitPerMinute": "Limite de Tokens par Minute",
    "link.unlimited": "Illimité",
    "link.keyManagement": "Gestion des Clés",
    "link.keyRotation": "Rotation des Clés",
    "link.sequential": "Séquentiel",
    "link.random": "Aléatoire",
    "link.keyFailover": "Basculement de Clé",
    "link.savePolicy": "Enregistrer la Politique",
    "link.policySaved": "Politique enregistrée",
    "link.policySaveFailed": "Échec de l'enregistrement de la politique",
    "link.noPolicy": "Aucune politique configurée",
    "link.loadPolicy": "Charger la Politique",
    "profile.loading": "Chargement du profil...",
    "profile.overview": "Aperçu du Profil",
    "profile.userId": "ID Utilisateur",
    "profile.lastUpdated": "Dernière Mise à Jour",
    "profile.codingStyle": "Style de Codage",
    "profile.namingConvention": "Convention de Nommage",
    "profile.indentationStyle": "Style d'Indentation",
    "profile.commentStyle": "Style de Commentaires",
    "profile.communication": "Communication",
    "profile.detailLevel": "Niveau de Détail",
    "profile.tone": "Ton",
    "profile.language": "Langue",
    "profile.confidence": "Confiance du Profil",
    "style.preview": "Aperçu du Style",
    "style.dimensions": "Dimensions",
    "style.applying": "Application...",
    "style.applyStyle": "Appliquer le Style",
    "style.reset": "Réinitialiser",
    "style.original": "Original",
    "style.styled": "Stylisé",
    "style.stats": "Statistiques de Style",
    "style.totalProfiles": "Profils Totaux",
    "style.totalSamples": "Échantillons Totaux",
    "skills.marketplace.convertToWorkflow": "Convertir en Workflow",
    "skills.marketplace.skillsMdNotFound": "SKILL.md introuvable (non trouvé dans la branche main ou master)",
    "skills.marketplace.skillsMdFetchFailed": "Échec de la récupération de SKILL.md",
    "skills.sortPopular": "Populaire",
    "skills.sortLatest": "Plus Récent",
    "skills.sortStars": "Étoiles",
    "skills.update": "Mettre à Jour",
    "skills.createTitle": "Créer une Nouvelle Compétence",
    "skills.create": "Créer",
    "skills.editTitle": "Modifier la Compétence : {{name}}",
    "skills.edit": "Modifier",
    "skills.patchTitle": "Corriger la Compétence : {{name}}",
    "skills.patch": "Corriger",
    "skills.name": "Nom de la Compétence",
    "skills.namePlaceholder": "ex. deploy-to-aws",
    "skills.nameRequired": "Le nom de la compétence est requis",
    "skills.description": "Description",
    "skills.descriptionPlaceholder": "Brève description de ce que fait cette compétence",
    "skills.content": "Instructions de la Compétence (Markdown)",
    "skills.contentPlaceholder": "# Ma Compétence\n\n## Aperçu\nDécrivez ce que fait cette compétence...\n\n## Étapes\n1. Étape un\n2. Étape deux\n...",
    "skills.contentRequired": "Le contenu de la compétence est requis",
    "skills.patchPlaceholder": "Décrivez le problème et la correction...",
    "skills.editPlaceholder": "Écrivez le corps complet de la compétence (le frontmatter sera préservé)...",
    "skills.loadMore": "Charger Plus",
    "skills.proposal.title": "Propositions de Compétences",
    "skills.proposal.empty": "Pas encore de propositions de compétences. Effectuez des tâches complexes de l'Agent pour générer des suggestions.",
    "skills.proposal.hint": "Ces compétences ont été générées automatiquement à partir de vos workflows Agent réussis. Examinez-les et créez-les pour automatiser des tâches similaires.",
    "skills.proposal.successWorkflow": "Workflow Réussi",
    "skills.proposal.failedWorkflow": "Workflow Échoué",
    "skills.proposal.partialSuccess": "Succès Partiel",
    "skills.proposal.confidence": "confiance",
    "skills.proposal.viewContent": "Voir le contenu suggéré",
    "skills.proposal.create": "Créer",
    "skills.proposal.dismiss": "Ignorer",
    "skills.proposal.created": "Compétence '{{name}}' créée",
    "skills.proposal.error": "Échec de la création de la compétence",
    "skills.extractAtomicSkills": "Extraire les Compétences Atomiques",
    "skills.decomposeSuccess": "Compétences atomiques extraites avec succès",
    "agent.askUserSupplementPlaceholder": "Entrée supplémentaire (facultatif)...",
    "agent.askUserSubmitted": "Soumis",
    "common.modeLabel": "Mode",
    "common.openDirectory": "Ouvrir le Répertoire",
}

fr.update(_fr_common_english)

# === GERMAN (de.json) translations ===
de = {
    "nav.link": "Verknüpfung",
    "chat.workspaceLocked": "Das Arbeitsverzeichnis kann nach Beginn der Konversation nicht mehr geändert werden",
    "chat.agentInitFailed": "Fehler beim Initialisieren der Agent-Sitzung",
    "chat.switchAgentModeNoConversation": "Bitte starten Sie zuerst eine neue Konversation, bevor Sie in den Agent-Modus wechseln",
    "chat.cancelled": "Abgebrochen",
    "chat.takePhoto": "Foto aufnehmen",
    "chat.recordAudio": "Audio aufnehmen",
    "chat.recordVideo": "Video aufnehmen",
    "chat.switchModeShortcut": "Tipp: Drücken Sie Shift+Tab zum schnellen Moduswechsel",
    "chat.batchArchiveToKnowledgeBase": "Stapelweise in Wissensdatenbank archivieren",
    "chat.saveAsWorkflow": "Als Workflow speichern",
    "chat.selectOneConversation": "Bitte wählen Sie eine Konversation aus",
    "chat.searchPastSessions": "Vergangene Sitzungen suchen",
    "chat.searchPastConversations": "Alle vergangenen Konversationen durchsuchen...",
    "chat.searchGo": "Los",
    "chat.searchResults": "{{count}} Ergebnis(se) in vergangenen Sitzungen",
    "chat.searchNoResults": "Noch keine Ergebnisse. Drücken Sie Enter oder Los zum Suchen.",
    "chat.insightsMemory": "Erkenntnisse & Gedächtnis",
    "chat.learningInsights": "Lernerkenntnisse",
    "chat.noInsights": "Noch keine Erkenntnisse. Sie sammeln sich während der Interaktion an.",
    "chat.flushToMemory": "Ins Langzeitgedächtnis speichern:",
    "chat.closedLoop": "Geschlossener Kreislauf",
    "chat.closedLoopLearning": "Geschlossenes Lernen",
    "chat.trajectories": "Trajektorien",
    "chat.successRate": "Erfolgsquote",
    "chat.insights": "Erkenntnisse",
    "chat.patterns": "Muster",
    "chat.closedLoopRunning": "Läuft",
    "chat.closedLoopStopped": "Gestoppt",
    "chat.nudgesPending": "Anstehende Nudges",
    "chat.pipeline": "Pipeline: Trajektorie → Muster → RL → Nudge → Gedächtnis/Fähigkeit",
    "chat.learnedPatterns": "Gelernte Muster",
    "chat.noPatternsYet": "Noch keine Muster. Sie entstehen während der Interaktion über Sitzungen hinweg.",
    "chat.noPatternsFilter": "Keine Muster entsprechen dem aktuellen Filter.",
    "chat.rlEngine": "RL-Engine",
    "chat.success": "Erfolg",
    "chat.quality": "Qualität",
    "chat.config": "Konfiguration",
    "chat.gamma": "γ (Diskont)",
    "chat.lambda": "λ (TD)",
    "chat.rewardScale": "Skalierung",
    "chat.entropyCoeff": "Entropie-Koeff",
    "chat.rewardWeights.task_completion": "Aufgabenabschluss",
    "chat.rewardWeights.tool_efficiency": "Werkzeugeffizienz",
    "chat.rewardWeights.reasoning_quality": "Schlussfolgerungsqualität",
    "chat.rewardWeights.error_recovery": "Fehlerbehebung",
    "chat.rewardWeights.user_feedback": "Benutzer-Feedback",
    "chat.rewardWeights.pattern_match": "Musterabgleich",
    "chat.exportTrainingData": "Trainingsdaten Exportieren",
    "chat.evolution": "Evolution",
    "chat.skillEvolution": "Fähigkeiten-Evolution",
    "chat.generation": "Generation",
    "chat.bestFitness": "Beste Fitness",
    "chat.status": "Status",
    "chat.converged": "Konvergiert",
    "chat.running": "Läuft",
    "chat.idle": "Inaktiv",
    "chat.fitnessCurve": "Fitnesskurve",
    "chat.improved": "Verbessert",
    "chat.noImprovement": "Keine Verbesserung",
    "chat.profile": "Profil",
    "chat.userProfile": "Benutzerprofil",
    "chat.style": "Stil",
    "chat.preferences": "Präferenzen",
    "chat.expertise": "Expertise",
    "chat.adaptingFromInteractions": "Anpassung aus Interaktionen...",
    "chat.rewindConversation": "Konversation Zurückspulen",
    "chat.rewindConfirmContent": "Dies löscht alle Nachrichten nach diesem Punkt. Diese Aktion kann nicht rückgängig gemacht werden.",
    "chat.rewind": "Zurückspulen",
    "chat.workflow.knowledgeExtract.name": "Geschäftswissensextraktion",
    "chat.workflow.knowledgeExtract.description": "Sprachunabhängiges Geschäftswissen aus Code für sprachübergreifende Refaktorierung extrahieren.",
    "chat.workflow.knowledgeToCode.name": "Wissen zu Code",
    "chat.workflow.knowledgeToCode.description": "Vollständige Code-Implementierung in der Zielsprache aus der Geschäftswissensbasis generieren, unterstützt sprachübergreifende Migration.",
    "chat.workflow.collectInputs.name": "Benutzereingaben Sammeln",
    "chat.workflow.collectInputs.description": "Zielsprache, Framework, Wissensdatenbank-ID, Ausgabeverzeichnis und andere Projektinformationen sammeln.",
    "chat.workflow.decompositionSaved": "Zerlegungs-Workflow erfolgreich gespeichert",
    "chat.workflow.semanticCheckTitle": "Ähnliche Fähigkeiten Gefunden",
    "chat.workflow.semanticCheckDescription": "Die folgenden generierten atomaren Fähigkeiten haben eine hohe semantische Ähnlichkeit mit bestehenden Fähigkeiten. Sie können die bestehende verwenden oder die generierte behalten.",
    "chat.workflow.semanticCheckApplied": "Fähigkeitsersetzung angewendet",
    "chat.workflow.skipSemanticCheck": "Überspringen",
    "chat.workflow.applySemanticCheck": "Anwenden",
    "chat.workflow.replaceWithExisting": "Bestehende Verwenden",
    "chat.workflow.keepGeneratedSkill": "Generierte Behalten",
    "chat.workflow.upgradeExisting": "Bestehende Aktualisieren",
    "chat.workflow.existingSkill": "Bestehende Fähigkeit",
    "chat.workflow.matchReasons": "Übereinstimmungsgründe",
    "chat.workflow.generatedSkill": "Generierte Fähigkeit",
    "chat.workflow.upgradeSkillTitle": "Fähigkeit Aktualisieren",
    "chat.workflow.upgradeSuggestion": "LLM-Aktualisierungsvorschlag",
    "chat.workflow.generatingUpgrade": "Aktualisierungsvorschlag wird generiert...",
    "chat.workflow.applyUpgrade": "Aktualisierung Anwenden",
    "chat.workflow.upgradeError": "Aktualisierungsvorschlag konnte nicht abgerufen werden",
    "chat.workflow.upgradedName": "Aktualisierter Name",
    "chat.workflow.inputSchema": "Eingabeschema",
    "chat.workflow.outputSchema": "Ausgabeschema",
    "chat.workflow.upgradeReasoning": "Aktualisierungsbegründung",
    "gateway.connectedTools": "Verbundene Werkzeuge",
    "settings.storage.changeDir": "Verzeichnis Ändern",
    "settings.storage.resetDir": "Auf Standard Zurücksetzen",
    "settings.storage.defaultDir": "Standard-Speicherort",
    "settings.storage.currentDir": "Aktuelles Speicherverzeichnis",
    "settings.storage.changeDirTitle": "Speicherverzeichnis Ändern",
    "settings.storage.changeDirConfirm": "Änderung des Speicherverzeichnisses auf diesen Speicherort bestätigen?",
    "settings.storage.changeDirNotEmpty": "Das Zielverzeichnis ist nicht leer. Fortsetzen kann sich mit bestehenden Dateien vermischen.",
    "settings.storage.migratePrompt": "Bestehende Dateien ins neue Verzeichnis migrieren?",
    "settings.storage.migrateYes": "Dateien Migrieren",
    "settings.storage.migrateNo": "Nicht Migrieren",
    "settings.storage.migrating": "Dateien werden migriert...",
    "settings.storage.changeDirSuccess": "Speicherverzeichnis geändert",
    "settings.storage.changeDirSuccessMigrate": "Speicherverzeichnis geändert, {{count}} Dateien migriert",
    "settings.storage.changeDirFailed": "Fehler beim Ändern des Speicherverzeichnisses",
    "settings.storage.resetDirConfirm": "Zurücksetzen auf den Standard-Speicherort bestätigen?",
    "settings.storage.resetDirSuccess": "Auf Standard-Speicherort zurückgesetzt",
    "settings.storage.dirNotWritable": "Zielverzeichnis ist nicht beschreibbar",
    "settings.storage.restartRequired": "Änderungen werden nach dem Neustart vollständig wirksam",
    "settings.storage.restartNow": "Jetzt Neustarten",
    "settings.storage.restartLater": "Später Neustarten",
}

_de_common_english = {
    "settings.scheduler.customTasks": "Benutzerdefinierte Aufgaben",
    "settings.scheduler.addTask": "Aufgabe Hinzufügen",
    "settings.scheduler.editTask": "Aufgabe Bearbeiten",
    "settings.scheduler.taskName": "Aufgabenname",
    "settings.scheduler.taskDescription": "Beschreibung",
    "settings.scheduler.intervalHours": "Intervall (Stunden)",
    "settings.scheduler.nextRunAt": "Nächste Ausführung",
    "settings.scheduler.lastRunAt": "Letzte Ausführung",
    "settings.scheduler.noTasks": "Keine benutzerdefinierten Aufgaben konfiguriert",
    "settings.scheduler.createTask": "Aufgabe Erstellen",
    "settings.scheduler.updateTask": "Aufgabe Aktualisieren",
    "settings.scheduler.deleteTask": "Aufgabe Löschen",
    "settings.scheduler.deleteTaskConfirm": "Diese Aufgabe löschen?",
    "settings.scheduler.pauseTask": "Pause",
    "settings.scheduler.resumeTask": "Fortsetzen",
    "settings.scheduler.taskActive": "Aktiv",
    "settings.scheduler.taskPaused": "Pausiert",
    "settings.scheduler.taskDisabled": "Deaktiviert",
    "settings.scheduler.selectInterval": "Intervall auswählen",
    "settings.scheduler.once": "Einmal",
    "settings.scheduler.daily": "Täglich",
    "settings.scheduler.weekly": "Wöchentlich",
    "settings.scheduler.monthly": "Monatlich",
    "settings.scheduler.schedule": "Zeitplan",
    "settings.scheduler.scheduleSettings": "Zeitplaneinstellungen",
    "settings.scheduler.scheduleType": "Zeitplantyp",
    "settings.scheduler.selectScheduleType": "Zeitplantyp auswählen",
    "settings.scheduler.scheduleInterval": "Intervall",
    "settings.scheduler.scheduleDaily": "Täglich",
    "settings.scheduler.scheduleWeekly": "Wöchentlich",
    "settings.scheduler.scheduleMonthly": "Monatlich",
    "settings.scheduler.scheduleAdvanced": "Erweitert",
    "settings.scheduler.weekdays": "Wochentage",
    "settings.scheduler.monday": "Mo",
    "settings.scheduler.tuesday": "Di",
    "settings.scheduler.wednesday": "Mi",
    "settings.scheduler.thursday": "Do",
    "settings.scheduler.friday": "Fr",
    "settings.scheduler.saturday": "Sa",
    "settings.scheduler.sunday": "So",
    "settings.scheduler.timeRanges": "Zeitbereiche",
    "settings.scheduler.startTime": "Start",
    "settings.scheduler.endTime": "Ende",
    "settings.scheduler.addTimeRange": "Zeitbereich Hinzufügen",
    "settings.scheduler.monthDay": "Tag des Monats",
    "settings.scheduler.dayOfMonth": "Tag {{day}}",
    "settings.scheduler.selectDayOfMonth": "Tag des Monats auswählen",
    "settings.scheduler.excludeHolidays": "Feiertage ausschließen",
    "settings.scheduler.excludeCustomDates": "Benutzerdefinierte Daten Ausschließen",
    "settings.scheduler.enterExcludeDates": "Auszuschließende Daten eingeben (JJJJ-MM-TT)",
    "settings.scheduler.intervalDesc": "Alle {{hours}} Stunden",
    "settings.scheduler.dailyDesc": "Täglich",
    "settings.scheduler.weeklyDesc": "Wöchentlich am {{days}}",
    "settings.scheduler.monthlyDesc": "Monatlich am Tag {{day}}",
    "settings.scheduler.advancedDesc": "Erweiterter Zeitplan",
    "settings.scheduler.selectTemplate": "Vorlage Auswählen",
    "settings.scheduler.workflowTemplates": "Workflow-Vorlagen",
    "settings.scheduler.reportTemplates": "Berichtsvorlagen",
    "settings.scheduler.workflowCodeReview": "Code-Review-Workflow",
    "settings.scheduler.workflowBugFix": "Bug-Fix-Workflow",
    "settings.scheduler.workflowDocGen": "Dokumentations-Workflow",
    "settings.scheduler.workflowTestGen": "Testgenerierungs-Workflow",
    "settings.scheduler.workflowRefactor": "Refactoring-Workflow",
    "settings.scheduler.workflowExplore": "Code-Explorations-Workflow",
    "settings.scheduler.workflowPerformance": "Leistungsoptimierungs-Workflow",
    "settings.scheduler.workflowKnowledgeExtract": "Wissensextraktions-Workflow",
    "settings.scheduler.workflowKnowledgeToCode": "Wissen-zu-Code-Workflow",
    "settings.localTools.title": "Lokale Werkzeuge",
    "settings.localTools.description": "Aktivierungs-/Deaktivierungsstatus integrierter Werkzeuge verwalten. Deaktivierte Werkzeuge erscheinen nicht in der verfügbaren Werkzeugliste des Agenten.",
    "settings.localTools.groupFetch": "Web-Abruf",
    "settings.localTools.groupSearchFile": "Dateisuche",
    "settings.localTools.groupFilesystem": "Dateisystem",
    "settings.localTools.groupSystem": "Systembefehle",
    "settings.localTools.groupSearch": "Websuche",
    "settings.localTools.groupKnowledge": "Wissensdatenbank",
    "settings.localTools.groupStorage": "Objektspeicher",
    "settings.localTools.groupSkills": "Fähigkeitenverwaltung",
    "settings.localTools.groupSession": "Sitzungssuche",
    "settings.localTools.groupMemory": "Gedächtnisverwaltung",
    "settings.tools.title": "Werkzeug-Manager",
    "settings.tools.tabBuiltin": "Integrierte Werkzeuge",
    "settings.tools.tabMcp": "MCP-Server",
    "settings.tools.tabGenerated": "Generierte Werkzeuge",
    "settings.tools.tabSemantic": "Semantische Prüfung",
    "settings.generatedTools.title": "Generierte Werkzeuge",
    "settings.generatedTools.description": "Prompt-Vorlagen-Werkzeuge, die aus der Zerlegung zusammengesetzter Fähigkeiten generiert wurden. Diese Werkzeuge verwenden LLM, um Prompts auszuführen und Funktionen zu simulieren.",
    "settings.generatedTools.toolName": "Werkzeugname",
    "settings.generatedTools.originalName": "Ursprünglicher Name",
    "settings.generatedTools.createdAt": "Erstellt Am",
    "settings.generatedTools.deleteConfirm": "Dieses generierte Werkzeug löschen?",
    "settings.generatedTools.deleteSuccess": "Erfolgreich gelöscht",
    "settings.generatedTools.total": "{{count}} generierte(s) Werkzeug(e)",
    "settings.generatedTools.empty": "Keine generierten Werkzeuge",
    "settings.toolSemanticCheck.title": "Semantische Werkzeugprüfung",
    "settings.toolSemanticCheck.description": "Ähnliche Werkzeuge finden und bestehende mit KI aktualisieren",
    "settings.toolSemanticCheck.searchPlaceholder": "Werkzeugname oder Beschreibung eingeben",
    "settings.toolSemanticCheck.emptySearch": "Bitte geben Sie einen Suchbegriff ein",
    "settings.toolSemanticCheck.noMatches": "Keine ähnlichen Werkzeuge gefunden",
    "settings.toolSemanticCheck.empty": "Geben Sie einen Suchbegriff ein, um ähnliche Werkzeuge zu finden",
    "settings.toolSemanticCheck.matches": "{{count}} Übereinstimmungen",
    "settings.toolSemanticCheck.checkingTool": "Suche nach Werkzeugen ähnlich zu {{tool}}",
    "settings.toolSemanticCheck.similarity": "Ähnlichkeit",
    "settings.toolSemanticCheck.upgrade": "Aktualisieren",
    "settings.toolSemanticCheck.upgradeModalTitle": "Werkzeug Aktualisieren",
    "settings.toolSemanticCheck.existingTool": "Bestehendes Werkzeug",
    "settings.toolSemanticCheck.generatedTool": "Generiertes Werkzeug",
    "settings.toolSemanticCheck.toolType": "Werkzeugtyp",
    "settings.toolSemanticCheck.noDescription": "Keine Beschreibung",
    "settings.toolSemanticCheck.performUpgrade": "Aktualisierung Durchführen",
    "settings.toolSemanticCheck.upgradeSuccess": "Werkzeug-Aktualisierungsvorschlag generiert",
    "settings.toolSemanticCheck.upgradeSuggestion": "Aktualisierungsvorschlag",
    "settings.toolSemanticCheck.reasoning": "Begründung",
    "settings.groupWorkspace": "Arbeitsbereich",
    "settings.defaultWorkspaceDir": "Standard-Arbeitsverzeichnis",
    "settings.userProfile.title": "Benutzerprofil",
    "settings.userProfile.overview": "Profilübersicht",
    "settings.userProfile.userId": "Benutzer-ID",
    "settings.userProfile.lastUpdated": "Zuletzt Aktualisiert",
    "settings.userProfile.codingStyle": "Codierungsstil",
    "settings.userProfile.namingConvention": "Namenskonvention",
    "settings.userProfile.indentationStyle": "Einrückungsstil",
    "settings.userProfile.commentStyle": "Kommentarstil",
    "settings.userProfile.communication": "Kommunikation",
    "settings.userProfile.detailLevel": "Detailgrad",
    "settings.userProfile.tone": "Tonfall",
    "settings.userProfile.language": "Sprache",
    "settings.userProfile.confidence": "Profilkonfidenz",
    "settings.userProfile.loading": "Profil wird geladen...",
    "link.title": "Verknüpfung",
    "link.searchGateways": "Gateways suchen",
    "link.noGateways": "Keine Gateway-Verbindungen",
    "link.selectGateway": "Gateway-Verbindung auswählen",
    "link.addGateway": "Gateway-Verbindung Hinzufügen",
    "link.gatewayName": "Verbindungsname",
    "link.gatewayType": "Gateway-Typ",
    "link.endpoint": "Endpunkt",
    "link.apiKey": "API-Schlüssel",
    "link.apiKeyPlaceholder": "Optional, leer lassen für keinen Schlüssel",
    "link.namePlaceholder": "z.B. OpenClaw-Prod",
    "link.nameRequired": "Bitte geben Sie einen Verbindungsnamen ein",
    "link.endpointRequired": "Bitte geben Sie einen Endpunkt ein",
    "link.addSuccess": "Gateway-Verbindung hinzugefügt",
    "link.addFailed": "Fehler beim Hinzufügen der Gateway-Verbindung",
    "link.deleteSuccess": "Gateway-Verbindung gelöscht",
    "link.deleteFailed": "Fehler beim Löschen der Gateway-Verbindung",
    "link.deleteConfirm": "Sind Sie sicher, dass Sie diese Gateway-Verbindung löschen möchten?",
    "link.typeCustom": "Benutzerdefiniert",
    "link.statusConnected": "Verbunden",
    "link.statusDisconnected": "Getrennt",
    "link.statusConnecting": "Verbinde",
    "link.statusError": "Fehler",
    "link.connect": "Verbinden",
    "link.disconnect": "Trennen",
    "link.latency": "Latenz",
    "link.overview": "Übersicht",
    "link.models": "Modelle",
    "link.skills": "Fähigkeiten",
    "link.policies": "Richtlinien",
    "link.newConversation": "Neues Gespräch",
    "link.syncedModels": "Synchronisierte Modelle",
    "link.syncedSkills": "Synchronisierte Fähigkeiten",
    "link.lastSync": "Letzte Synchronisierung",
    "link.recentActivity": "Letzte Aktivität",
    "link.noActivity": "Noch keine Aktivität",
    "link.autoSyncModels": "Modelle automatisch synchronisieren",
    "link.autoSyncSkills": "Fähigkeiten automatisch synchronisieren",
    "link.syncAllModels": "Alle Modelle Synchronisieren",
    "link.syncAllSkills": "Alle Fähigkeiten Synchronisieren",
    "link.syncAllSuccess": "Synchronisierung erfolgreich",
    "link.syncAllFailed": "Synchronisierung fehlgeschlagen",
    "link.pushModelsSuccess": "Modelle erfolgreich übertragen",
    "link.pushModelsFailed": "Fehler beim Übertragen der Modelle",
    "link.pushSkillsSuccess": "Fähigkeiten erfolgreich übertragen",
    "link.pushSkillsFailed": "Fehler beim Übertragen der Fähigkeiten",
    "link.modelName": "Modellname",
    "link.providerName": "Anbieter",
    "link.syncStatus": "Synchronisierungsstatus",
    "link.syncStatusSynced": "Synchronisiert",
    "link.syncStatusPending": "Ausstehend",
    "link.syncStatusFailed": "Fehlgeschlagen",
    "link.syncStatusNotSelected": "Nicht Ausgewählt",
    "link.skillName": "Fähigkeitsname",
    "link.skillVersion": "Version",
    "link.noModels": "Keine Modell-Synchronisierungsdatensätze",
    "link.noSkills": "Keine Fähigkeiten-Synchronisierungsdatensätze",
    "link.push": "Übertragen",
    "link.routingPolicy": "Routing-Richtlinie",
    "link.routeStrategy": "Routing-Strategie",
    "link.roundRobin": "Round Robin",
    "link.leastLatency": "Geringste Latenz",
    "link.weighted": "Gewichtet",
    "link.modelFallback": "Modell-Fallback",
    "link.rateLimiting": "Ratenbegrenzung",
    "link.globalRpm": "Global RPM",
    "link.perModelRpm": "Pro-Modell RPM",
    "link.tokenLimitPerMinute": "Token-Limit pro Minute",
    "link.unlimited": "Unbegrenzt",
    "link.keyManagement": "Schlüsselverwaltung",
    "link.keyRotation": "Schlüsselrotation",
    "link.sequential": "Sequenziell",
    "link.random": "Zufällig",
    "link.keyFailover": "Schlüssel-Failover",
    "link.savePolicy": "Richtlinie Speichern",
    "link.policySaved": "Richtlinie gespeichert",
    "link.policySaveFailed": "Fehler beim Speichern der Richtlinie",
    "link.noPolicy": "Keine Richtlinie konfiguriert",
    "link.loadPolicy": "Richtlinie Laden",
    "profile.loading": "Profil wird geladen...",
    "profile.overview": "Profilübersicht",
    "profile.userId": "Benutzer-ID",
    "profile.lastUpdated": "Zuletzt Aktualisiert",
    "profile.codingStyle": "Codierungsstil",
    "profile.namingConvention": "Namenskonvention",
    "profile.indentationStyle": "Einrückungsstil",
    "profile.commentStyle": "Kommentarstil",
    "profile.communication": "Kommunikation",
    "profile.detailLevel": "Detailgrad",
    "profile.tone": "Tonfall",
    "profile.language": "Sprache",
    "profile.confidence": "Profilkonfidenz",
    "style.preview": "Stilvorschau",
    "style.dimensions": "Dimensionen",
    "style.applying": "Wird angewendet...",
    "style.applyStyle": "Stil Anwenden",
    "style.reset": "Zurücksetzen",
    "style.original": "Original",
    "style.styled": "Gestylt",
    "style.stats": "Stilstatistiken",
    "style.totalProfiles": "Profile Gesamt",
    "style.totalSamples": "Stichproben Gesamt",
    "skills.marketplace.convertToWorkflow": "In Workflow Konvertieren",
    "skills.marketplace.skillsMdNotFound": "SKILL.md nicht gefunden (nicht im main- oder master-Branch gefunden)",
    "skills.marketplace.skillsMdFetchFailed": "Fehler beim Abrufen von SKILL.md",
    "skills.sortPopular": "Beliebt",
    "skills.sortLatest": "Neueste",
    "skills.sortStars": "Sterne",
    "skills.update": "Aktualisieren",
    "skills.createTitle": "Neue Fähigkeit Erstellen",
    "skills.create": "Erstellen",
    "skills.editTitle": "Fähigkeit Bearbeiten: {{name}}",
    "skills.edit": "Bearbeiten",
    "skills.patchTitle": "Fähigkeit Patchen: {{name}}",
    "skills.patch": "Patchen",
    "skills.name": "Fähigkeitsname",
    "skills.namePlaceholder": "z.B. deploy-to-aws",
    "skills.nameRequired": "Fähigkeitsname ist erforderlich",
    "skills.description": "Beschreibung",
    "skills.descriptionPlaceholder": "Kurze Beschreibung, was diese Fähigkeit tut",
    "skills.content": "Fähigkeitsanweisungen (Markdown)",
    "skills.contentPlaceholder": "# Meine Fähigkeit\n\n## Übersicht\nBeschreiben Sie, was diese Fähigkeit tut...\n\n## Schritte\n1. Schritt eins\n2. Schritt zwei\n...",
    "skills.contentRequired": "Fähigkeitsinhalt ist erforderlich",
    "skills.patchPlaceholder": "Beschreiben Sie das Problem und die Lösung...",
    "skills.editPlaceholder": "Vollständigen Fähigkeitsinhalt schreiben (Frontmatter bleibt erhalten)...",
    "skills.loadMore": "Mehr Laden",
    "skills.proposal.title": "Fähigkeitsvorschläge",
    "skills.proposal.empty": "Noch keine Fähigkeitsvorschläge. Führen Sie komplexe Agent-Aufgaben aus, um Vorschläge zu generieren.",
    "skills.proposal.hint": "Diese Fähigkeiten wurden automatisch aus Ihren erfolgreichen Agent-Workflows generiert. Überprüfen und erstellen Sie sie, um ähnliche Aufgaben zu automatisieren.",
    "skills.proposal.successWorkflow": "Erfolgreicher Workflow",
    "skills.proposal.failedWorkflow": "Fehlgeschlagener Workflow",
    "skills.proposal.partialSuccess": "Teilweiser Erfolg",
    "skills.proposal.confidence": "Konfidenz",
    "skills.proposal.viewContent": "Vorgeschlagenen Inhalt anzeigen",
    "skills.proposal.create": "Erstellen",
    "skills.proposal.dismiss": "Verwerfen",
    "skills.proposal.created": "Fähigkeit '{{name}}' erstellt",
    "skills.proposal.error": "Fehler beim Erstellen der Fähigkeit",
    "skills.extractAtomicSkills": "Atomare Fähigkeiten Extrahieren",
    "skills.decomposeSuccess": "Atomare Fähigkeiten erfolgreich extrahiert",
    "agent.askUserSupplementPlaceholder": "Zusätzliche Eingabe (optional)...",
    "agent.askUserSubmitted": "Eingereicht",
    "common.modeLabel": "Modus",
    "common.openDirectory": "Verzeichnis Öffnen",
}

de.update(_de_common_english)

# === Function to set nested value in dict ===
def set_nested(data, path, value):
    """Set a nested value using dot-notation path."""
    keys = path.split(".")
    d = data
    for key in keys[:-1]:
        if key not in d:
            return False
        d = d[key]
    last_key = keys[-1]
    if last_key in d:
        d[last_key] = value
        return True
    return False

# === Process each language ===
langs = [
    ("ko.json", ko),
    ("es.json", es),
    ("fr.json", fr),
    ("de.json", de),
]

for filename, translations in langs:
    filepath = os.path.join(base, filename)
    with open(filepath, "r", encoding="utf-8") as f:
        data = json.load(f)

    replaced = 0
    not_found = 0
    for path, value in translations.items():
        if set_nested(data, path, value):
            replaced += 1
        else:
            not_found += 1
            print(f"[{filename}] NOT FOUND: {path}")

    with open(filepath, "w", encoding="utf-8") as f:
        json.dump(data, f, ensure_ascii=False, indent=2)
        f.write("\n")

    print(f"[{filename}] Replaced: {replaced}, Not found: {not_found}")
