// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ModelParamOverrides = { temperature: number | null, maxTokens: number | null, topP: number | null, frequencyPenalty: number | null, 
/**
 * When true, the provider adapter should send `max_completion_tokens`
 * instead of `max_tokens` (required by OpenAI o-series models).
 */
useMaxCompletionTokens: boolean | null, 
/**
 * When true, system messages are converted to user messages
 * (for models that don't support the system role).
 */
noSystemRole: boolean | null, 
/**
 * When true, always include max_tokens in the request
 * (falls back to 4096 if conversation.max_tokens is not set).
 */
forceMaxTokens: boolean | null, 
/**
 * Thinking parameter format for the provider API.
 * "reasoning_effort" (default/OpenAI) or "enable_thinking" (SiliconFlow).
 */
thinkingParamStyle: string | null, 
/**
 * Delay in milliseconds before each API request to this model.
 * Used to avoid hitting rate limits (e.g. 429 errors) on providers
 * with strict per-model rate quotas.
 */
requestDelayMs: bigint | null, };
