// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Model } from "./Model";
import type { ProviderKey } from "./ProviderKey";
import type { ProviderProxyConfig } from "./ProviderProxyConfig";
import type { ProviderType } from "./ProviderType";

export type ProviderConfig = {
  id: string;
  name: string;
  provider_type: ProviderType;
  api_host: string;
  api_path: string | null;
  enabled: boolean;
  models: Array<Model>;
  keys: Array<ProviderKey>;
  proxy_config: ProviderProxyConfig | null;
  /**
   * 工具调用模式：None=按 provider_type 推断；"native"=模型原生 function calling；
   * "managed"=由 AxAgent 通过提示词注入 + 文本解析模拟（用于 Chat2API 等无原生 tool 接口的网关）
   */
  tool_adaptation: string | null;
  /**
   * 托管模式下的 marker 前缀（仅 tool_adaptation="managed" 时生效）。
   * None 或空字符串 = 使用默认值 "CHAT2API"。
   */
  tool_adaptation_marker_prefix: string | null;
  custom_headers: string | null;
  icon: string | null;
  builtin_id: string | null;
  sort_order: number;
  created_at: bigint;
  updated_at: bigint;
};
