// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ProviderProxyConfig = {
  proxy_type: string | null;
  proxy_address: string | null;
  proxy_port: number | null;
};
