// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ProviderProxyConfig = { proxyType: string | null; proxyAddress: string | null; proxyPort: number | null };
