export type AgentPermissionMode = "default" | "accept_edits" | "full_access";
export type AgentRuntimeStatus = "idle" | "running" | "waiting_approval" | "completed" | "error";
export type ApprovalStatus = "pending" | "approved" | "denied";

export interface AgentSession {
  id: string;
  conversation_id: string;
  cwd?: string;
  workspace_locked?: boolean;
  permission_mode: AgentPermissionMode;
  runtime_status: AgentRuntimeStatus;
  total_tokens: number;
  total_cost_usd: number;
}

// --- Event payload types (all tool-related events carry assistantMessageId anchor) ---

export interface ToolUseEvent {
  conversationId: string;
  assistantMessageId: string;
  toolUseId: string;
  toolName: string;
  input: Record<string, unknown>;
  executionId?: string;
}

export interface ToolStartEvent {
  conversationId: string;
  assistantMessageId: string;
  toolUseId: string;
  toolName: string;
  input: Record<string, unknown>;
}

export interface ToolResultEvent {
  conversationId: string;
  assistantMessageId: string;
  toolUseId: string;
  toolName: string;
  content: string;
  isError: boolean;
}

export interface PermissionRequestEvent {
  conversationId: string;
  assistantMessageId: string;
  toolUseId: string;
  toolName: string;
  input: Record<string, unknown>;
  riskLevel: "read_only" | "write" | "execute";
  /** The request_id generated by ChannelPermissionPrompter, used to reply via agent_approve */
  requestId: string;
}

export interface AskUserEvent {
  conversationId: string;
  assistantMessageId: string;
  askId: string;
  question: string;
  options?: string[];
}

export interface AgentDoneEvent {
  conversationId: string;
  assistantMessageId: string;
  text: string;
  thinking?: string;
  usage?: { input_tokens: number; output_tokens: number };
  numTurns?: number;
  costUsd?: number;
  blocks?: Array<{
    type: "text" | "tool_use" | "tool_result";
    text?: string;
    id?: string;
    name?: string;
    input?: string;
    toolUseId?: string;
    toolName?: string;
    output?: string;
    isError?: boolean;
  }>;
}

export interface AgentErrorEvent {
  conversationId: string;
  assistantMessageId?: string;
  message: string;
}

export interface AgentCancelledEvent {
  conversationId: string;
  assistantMessageId?: string;
  reason: string;
}

export interface AgentStatusEvent {
  conversationId: string;
  message: string;
}

export interface AgentRateLimitEvent {
  conversationId: string;
  retryAfterMs: number;
  message: string;
}

export interface AgentStreamTextEvent {
  conversationId: string;
  assistantMessageId: string;
  text: string;
}

export interface AgentStreamThinkingEvent {
  conversationId: string;
  assistantMessageId: string;
  thinking: string;
}

export interface WorkflowStepStartEvent {
  conversationId: string;
  assistantMessageId: string;
  type: "workflow_step_start";
  stepId: string;
  stepGoal: string;
  agentRole: string;
}

export interface WorkflowStepCompleteEvent {
  conversationId: string;
  assistantMessageId: string;
  type: "workflow_step_complete";
  stepId: string;
  stepGoal: string;
  result: string;
}

export interface WorkflowStepErrorEvent {
  conversationId: string;
  assistantMessageId: string;
  type: "workflow_step_error";
  stepId: string;
  error: string;
}

export interface WorkflowStartEvent {
  conversationId: string;
  assistantMessageId: string;
  type: "workflow_start";
  workflowId: string;
}

export interface WorkflowCompleteEvent {
  conversationId: string;
  assistantMessageId: string;
  workflowId: string;
  success: boolean;
}

export type WorkflowEvent =
  | WorkflowStepStartEvent
  | WorkflowStepCompleteEvent
  | WorkflowStepErrorEvent
  | WorkflowStartEvent;

// --- Frontend runtime state ---

export interface ToolCallState {
  toolUseId: string;
  toolName: string;
  input: Record<string, unknown>;
  assistantMessageId: string;
  executionStatus: "queued" | "running" | "success" | "failed" | "cancelled";
  approvalStatus?: ApprovalStatus;
  output?: string;
  isError?: boolean;
}

// --- Sub-agent card event ---

export interface SubAgentCardEvent {
  conversationId: string;
  agentType: string;
  agentName: string;
  description: string;
  status: "running" | "completed" | "failed";
  childConversationId?: string;
  childSessionId?: string;
}

export interface SubAgentCardData {
  id: string; // unique card ID (childConversationId)
  conversationId: string;
  agentType: string;
  agentName: string;
  description: string;
  status: "running" | "completed" | "failed";
  childConversationId?: string;
  childSessionId?: string;
}
