// SPDX-License-Identifier: AGPL-3.0-only

// 消息主题分组 — 对话内消息按主题自动/手动分组
import i18n from "@/i18n";
import { useConversationStore } from "@/stores/domain/conversationStore";
import { create } from "zustand";

export interface TopicGroup {
  id: string;
  label: string;
  messageIds: string[];
  collapsed: boolean;
  autoGenerated: boolean;
}

interface TopicGroupStore {
  groupsByConversation: Record<string, TopicGroup[]>;
  enabledByConversation: Record<string, boolean>;

  setEnabled: (conversationId: string, enabled: boolean) => void;
  autoDetect: (conversationId: string) => void;
  toggleCollapse: (conversationId: string, groupId: string) => void;
  renameGroup: (conversationId: string, groupId: string, label: string) => void;
  deleteGroup: (conversationId: string, groupId: string) => void;
  mergeUp: (conversationId: string, groupId: string) => void;
  splitGroup: (
    conversationId: string,
    groupId: string,
    splitAfterIndex: number,
  ) => void;
}

let _idCounter = 0;
const genId = () => `tg_${Date.now()}_${_idCounter++}`;

/** 取消息前 40 字符做摘要 */
function summarize(content: string, max = 40): string {
  const s = content.replace(/\n+/g, " ").trim();
  return s.length > max ? s.slice(0, max) + "…" : s;
}

export const useTopicGroupStore = create<TopicGroupStore>((set, get) => ({
  groupsByConversation: {},
  enabledByConversation: {},

  setEnabled: (conversationId, enabled) => {
    set((s) => ({
      enabledByConversation: {
        ...s.enabledByConversation,
        [conversationId]: enabled,
      },
    }));
    if (enabled) {
      get().autoDetect(conversationId);
    }
  },

  autoDetect: (conversationId) => {
    const msgs = useConversationStore
      .getState()
      .messages.filter(
        (m) => m.isActive !== false && m.conversationId === conversationId,
      );
    if (msgs.length < 3) {
      return;
    }

    // 已有分组时做增量更新：保留用户手动状态（折叠/重命名/合并），
    // 仅把新增消息追加进当前组或开新组，避免每次消息变化全量重建导致
    // 手动状态丢失、新消息永远不在任何分组里。
    const prevGroups = get().groupsByConversation[conversationId];
    if (prevGroups && prevGroups.length > 0) {
      const knownIds = new Set<string>();
      for (const g of prevGroups) {
        for (const mid of g.messageIds) {
          knownIds.add(mid);
        }
      }
      const newMsgs = msgs.filter((m) => !knownIds.has(m.id));
      if (newMsgs.length === 0) {
        return;
      }
      const groups = prevGroups.map((g) => ({
        ...g,
        messageIds: [...g.messageIds],
      }));
      let currentGroup = groups[groups.length - 1] ?? null;
      for (const msg of newMsgs) {
        if (msg.role === "user") {
          currentGroup = {
            id: genId(),
            label: summarize(msg.content),
            messageIds: [msg.id],
            collapsed: false,
            autoGenerated: true,
          };
          groups.push(currentGroup);
        } else if (currentGroup) {
          // assistant / tool → 归入当前（最后一）组
          currentGroup.messageIds.push(msg.id);
        } else if (msg.parentMessageId) {
          // 无当前组但出现 assistant 消息：父 user 消息可能不在已加载范围内，
          // 补建一组（父消息 id + 本条 assistant id）
          currentGroup = {
            id: genId(),
            label: summarize(i18n.t("topicGroup.linkedReply")),
            messageIds: [msg.parentMessageId, msg.id],
            collapsed: false,
            autoGenerated: true,
          };
          groups.push(currentGroup);
        }
      }
      set((s) => ({
        groupsByConversation: {
          ...s.groupsByConversation,
          [conversationId]: groups,
        },
      }));
      return;
    }

    const groups: TopicGroup[] = [];
    let currentIds: string[] = [];
    let currentLabel = "";

    for (const msg of msgs) {
      if (msg.role === "user") {
        // 遇到新用户消息 → 开始新组
        if (currentIds.length > 0) {
          groups.push({
            id: genId(),
            label: currentLabel || summarize(msg.content),
            messageIds: [...currentIds],
            collapsed: false,
            autoGenerated: true,
          });
        }
        currentIds = [msg.id];
        currentLabel = summarize(msg.content);
      } else {
        // assistant / tool → 归入当前组
        if (currentIds.length === 0 && msg.parentMessageId) {
          currentIds.push(msg.parentMessageId);
          currentLabel = summarize(i18n.t("topicGroup.linkedReply"));
        }
        currentIds.push(msg.id);
      }

      // assistant 内容中的 `---` 或 `## ` 触发切分（支持独立行和前后换行）
      const sepMatch = msg.content.match(/^---\s*$|\n---\n|\n## /m);
      if (msg.role === "assistant" && sepMatch) {
        const parts = msg.content.split(/\n(?:---\s*$|(?=## ))\n?/m);
        if (parts.length > 1 && currentIds.length > 0) {
          groups.push({
            id: genId(),
            label: currentLabel || summarize(parts[0]),
            messageIds: [...currentIds],
            collapsed: false,
            autoGenerated: true,
          });
          currentIds = [msg.id];
          currentLabel = summarize(parts[parts.length - 1] || msg.content);
        }
      }
    }

    // 最后一组
    if (currentIds.length > 0) {
      groups.push({
        id: genId(),
        label: currentLabel || i18n.t("topicGroup.untitled"),
        messageIds: [...currentIds],
        collapsed: false,
        autoGenerated: true,
      });
    }

    set((s) => ({
      groupsByConversation: {
        ...s.groupsByConversation,
        [conversationId]: groups,
      },
    }));
  },

  toggleCollapse: (conversationId, groupId) => {
    set((s) => {
      const conv = s.groupsByConversation[conversationId];
      if (!conv) {
        return {};
      }
      return {
        groupsByConversation: {
          ...s.groupsByConversation,
          [conversationId]: conv.map((g) => g.id === groupId ? { ...g, collapsed: !g.collapsed } : g),
        },
      };
    });
  },

  renameGroup: (conversationId, groupId, label) => {
    set((s) => {
      const conv = s.groupsByConversation[conversationId];
      if (!conv) {
        return {};
      }
      return {
        groupsByConversation: {
          ...s.groupsByConversation,
          [conversationId]: conv.map((g) => g.id === groupId ? { ...g, label, autoGenerated: false } : g),
        },
      };
    });
  },

  deleteGroup: (conversationId, groupId) => {
    set((s) => {
      const conv = s.groupsByConversation[conversationId];
      if (!conv) {
        return {};
      }
      const idx = conv.findIndex((g) => g.id === groupId);
      if (idx < 0) {
        return {};
      }
      const merged = [...conv];
      // 将被删组的消息合并到上一组，避免消息从视图中消失
      if (idx > 0) {
        merged[idx - 1] = {
          ...merged[idx - 1],
          messageIds: [
            ...merged[idx - 1].messageIds,
            ...merged[idx].messageIds,
          ],
          autoGenerated: merged[idx - 1].autoGenerated,
        };
      }
      merged.splice(idx, 1);
      return {
        groupsByConversation: {
          ...s.groupsByConversation,
          [conversationId]: merged,
        },
      };
    });
  },

  mergeUp: (conversationId, groupId) => {
    set((s) => {
      const conv = s.groupsByConversation[conversationId];
      if (!conv) {
        return {};
      }
      const idx = conv.findIndex((g) => g.id === groupId);
      if (idx <= 0) {
        return {};
      }
      const merged = [...conv];
      // 手动合并操作清除自动生成标记
      merged[idx - 1] = {
        ...merged[idx - 1],
        messageIds: [...merged[idx - 1].messageIds, ...merged[idx].messageIds],
        autoGenerated: merged[idx - 1].autoGenerated && merged[idx].autoGenerated,
      };
      merged.splice(idx, 1);
      return {
        groupsByConversation: {
          ...s.groupsByConversation,
          [conversationId]: merged,
        },
      };
    });
  },

  splitGroup: (conversationId, groupId, splitAfterIndex) => {
    set((s) => {
      const conv = s.groupsByConversation[conversationId];
      if (!conv) {
        return {};
      }
      const g = conv.find((x) => x.id === groupId);
      if (!g || splitAfterIndex >= g.messageIds.length - 1) {
        return {};
      }
      const left = g.messageIds.slice(0, splitAfterIndex + 1);
      const right = g.messageIds.slice(splitAfterIndex + 1);
      const idx = conv.findIndex((x) => x.id === groupId);
      const updated = [...conv];
      updated[idx] = { ...g, messageIds: left, autoGenerated: false };
      updated.splice(idx + 1, 0, {
        id: genId(),
        label: i18n.t("topicGroup.splitTopic"),
        messageIds: right,
        collapsed: false,
        autoGenerated: false,
      });
      return {
        groupsByConversation: {
          ...s.groupsByConversation,
          [conversationId]: updated,
        },
      };
    });
  },
}));
