#!/usr/bin/env python3
"""
Patch Android build.gradle.kts with signing configuration.

Reads keystore.properties (generated by CI) and injects signingConfigs
into the android block of build.gradle.kts.

Usage:
    python3 scripts/patch-android-signing.py src-tauri/gen/android/app/build.gradle.kts
"""

import os
import re
import sys


def main():
    if len(sys.argv) < 2:
        print("Usage: patch-android-signing.py <build.gradle.kts>")
        sys.exit(1)

    build_file = sys.argv[1]
    props_file = os.path.join(os.path.dirname(build_file), os.pardir, "keystore.properties")

    if not os.path.exists(build_file):
        print(f"build.gradle.kts not found: {build_file}")
        sys.exit(1)

    if not os.path.exists(props_file):
        print(f"keystore.properties not found: {props_file}")
        sys.exit(1)

    # Read keystore properties
    props = {}
    with open(props_file, "r") as f:
        for line in f:
            line = line.strip()
            if "=" in line:
                k, v = line.split("=", 1)
                props[k.strip()] = v.strip()

    store_file = props.get("storeFile", "release.jks")
    store_password = props.get("storePassword", "")
    key_alias = props.get("keyAlias", "")
    key_password = props.get("keyPassword", "")

    # Read existing build.gradle.kts
    with open(build_file, "r") as f:
        content = f.read()

    signing_config = f"""
    signingConfigs {{
        create("release") {{
            storeFile = file("{store_file}")
            storePassword = "{store_password}"
            keyAlias = "{key_alias}"
            keyPassword = "{key_password}"
        }}
    }}
"""

    # Inject signingConfigs before the "buildTypes" block in "android"
    # If signingConfigs already exists, don't duplicate
    if 'signingConfigs' in content:
        print("signingConfigs already exists in build.gradle.kts, skipping injection")
        # Still ensure the release buildType references it
        if 'signingConfig = signingConfigs.getByName("release")' not in content:
            print("Warning: release signing config reference not found")
    else:
        # Insert signingConfigs block before the first buildTypes block inside android { }
        # Find the "android {" block and insert before its "buildTypes"
        content = re.sub(
            r'(buildTypes\s*\{)',
            signing_config + r"\1",
            content,
            count=1,
        )

        # 在 buildTypes 块内的 getByName("release") { ... } body 开头注入 signingConfig。
        # 注：必须匹配带左大括号的完整模式，否则原 block 的 `{` 会留在替换文本之后，
        # 形成 `} {` 语法错误（Gradle Kotlin DSL 报 "Only one lambda expression is allowed"）。
        # 用正则允许 getByName("release") 和 { 之间任意空白（换行/空格/注释）。
        new_content, n = re.subn(
            r'(getByName\(\s*"release"\s*\)\s*\{)',
            r'\1\n            signingConfig = signingConfigs.getByName("release")',
            content,
            count=1,
        )
        if n == 0:
            print("Warning: getByName(\"release\") block not found, signingConfig not injected")
        else:
            content = new_content

    with open(build_file, "w") as f:
        f.write(content)

    print(f"Patched {build_file} with signing configuration from {props_file}")
    print(f"  storeFile: {store_file}")


if __name__ == "__main__":
    main()
